### ISSUE TITLE
Hostgroup_name permissions filter also limits visible hostgroups

### ISSUE THREAD

**Issue by bl4kd3th** [Icinga/icingaweb2#3192] opened 2017-12-05 16:53 UTC
## Expected Behavior
Here is the text from the documentation: 
> "The only filter directive that is available in a default installation, is the monitoring/filter/objects directive, defined by the monitoring module, that can be used to apply filter to hosts and services." 
[https://www.icinga.com/docs/icingaweb2/latest/doc/06-Security/#restrictions](url) 

Per the text above, I expect the filter to limit visible hosts (not hostgroups) based on hostgroup membership.

What I expected to see after applying filter for Infrastructure Servers:
![image](https://user-images.githubusercontent.com/1704681/33619103-f391a45a-d9a9-11e7-9903-8c44669001f8.png)

## Current Behavior
If you apply a hostgroup_name filter in "monitoring/filter/objects" and a host has multiple hostgroups, it will hide hostgroups on the host that do not match the filter. 

What I see on the same host when applying the Infrastructure Servers filter:
![image](https://user-images.githubusercontent.com/1704681/33619144-0dcfa7ea-d9aa-11e7-9b4e-2fc2026ee755.png)

## Steps to Reproduce (for bugs)
1. Apply multiple hostgroups to a host.
2. In Authentication, update a role and set "monitoring/filter/objects" to "hostgroup_name=GroupName", where GroupName matches one of the hostgroups applied in step 1.
![image](https://user-images.githubusercontent.com/1704681/33619183-215f3d0c-d9aa-11e7-859a-c656cbf89cc7.png)
3. Apply role to a user and login as that user.
4. View the host that you modified in step 1. You will see only the hostgroup defined in step 2, but not any of the other hostgroups applied in step 1.

## Context
I am trying to set up roles to limit visibility of hosts for a user. I have multiple hostgroups on a host, such as system type (SQL), environment (Prod), and app owner (InternalApps). If I use a host_name filter, I am able to see all hostgroups on a host (which is expected). However, I cannot expect that all hosts will follow a predictable naming convention in the future. I would prefer to manage host visibility using hostgroups. The hostgroup_name filter prevents me from seeing the additional hostgroups. When I set the hostgroup_name filter to SQL, I can no longer see the Prod or InternalApps hostgroups on that host. This makes it more difficult to differentiate the host types and determine course of action when actively monitoring hosts through the interface.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.5.0
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: CentOS Linux release 7.4.1708 (Core)
* Enabled features (`icinga2 feature list`): api checker ido-mysql influxdb mainlog notification
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: [hostname]
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 5 Zones.
information/ConfigItem: Instantiated 4 Endpoints.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 UserGroups.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 1473 Notifications.
information/ConfigItem: Instantiated 210 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 419 Hosts.
information/ConfigItem: Instantiated 6 HostGroups.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 2 Users.
information/ConfigItem: Instantiated 8 Comments.
information/ConfigItem: Instantiated 1 ServiceGroup.
information/ConfigItem: Instantiated 1054 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by lippserd** [comment] 2018-06-20 14:15
Hi,

Thanks for the report. We'll have a look at this one.

Best,
Eric

**Comment by lippserd** [comment] 2018-06-20 15:02
Closing as duplicate of #3349.

**Closed by lippserd** 2018-06-20 15:02 UTC
Labels: bug
