### ISSUE TITLE
Icinga Web 2 Bug while going through Web setup API User

### ISSUE THREAD

**Issue by Nathaniel-Donahue** [Icinga/icingaweb2#4209] opened 2020-07-16 13:41 UTC
Hi there!

## The Issue:
The Issue appears in the Web configuration when you set up Icinga Web 2. Inside the setup routine you hit a side that needs some pre-configured information like the credentials for the API User. So now you have to put in some wrong credentials and then check if its right and an error will appear then you can change the password to the right one and check again but the error still appears and you can't go on.

## Possible Solution:
A workaround is: go one site back refresh and then go to the site with the API user again. The side kept your credentials so you don't have to change something. you directly can check if the settings are right and no error will appear and you can go on.

## My Environment:
operating System: Centos 7
Used Browser is Google Chrome - Version 83.0.4103.97 (Offizieller Build) (64-Bit)

Just a normal installation on 
``` 
[root@icinga2 ~]# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.4-1)

[root@icinga2 ~]# icingacli --version
Icinga Web 2  2.8.1     
Git Commit    233bd29e4104125b4e5ef631e8c16dde33dadd9a 
PHP Version   7.3.11    
MODULE      VERSION   
monitoring  2.8.1 
``` 

## Some Screenshots:

![Bildschirmfoto vom 2020-07-16 11-13-42](https://user-images.githubusercontent.com/56820910/87671640-f8587500-c771-11ea-837c-7c5ef4a1d966.png)
![Bildschirmfoto vom 2020-07-16 10-11-27](https://user-images.githubusercontent.com/56820910/87671642-f8f10b80-c771-11ea-9d93-5411ba9aa56b.png)

The Password in the Screenshots is right.

Kind regards
Nathaniel

**Comment by Al2Klimov** [comment] 2020-08-06 12:59
Hello @Nathaniel-Donahue and thank you for reporting!

Are these the steps you've performed?

https://youtu.be/9UCt9DphbD0

(Feel free to skip the first 9min or so.)

Best,
AK

**Comment by nilmerg** [comment] 2020-08-10 08:49
Can't reproduce this on my end. Please come over if you encounter this issue again.

**Comment by nilmerg** [comment] 2020-11-17 07:41
I'm closing this now. If you'll encounter it again, please re-open.

**Closed by nilmerg** 2020-11-17 07:41 UTC
Labels: needs-feedback
