### ISSUE TITLE
Filter for custom vars that are not set

### ISSUE THREAD

**Issue by mrimann** [Icinga/icingaweb2#4080] opened 2020-02-26 04:54 UTC
We set a custom variable `vars.production_level = x` to hosts and services. Depending on this, several things behave differently (e.g. critical infrastructure get's level 5, causing loss of sleep in case of a problem - whereas other checks with e.g. level 2 will just create tickets to be tackled the other day).

We are able to filter for for both hosts + services and select only the hosts/services of a given value of this custom variable.

For a cross-check, I'd like to be able to filter for that custom variable to be "NULL" or "undefined" or "n/a", to be able to see hosts/services where we accidentally forgot to add this variable.

As of now, searching for "" or an empty field just results in an empty search result:

![image](https://user-images.githubusercontent.com/1093784/75313146-4a007180-585c-11ea-8785-e566ef1d8a7c.png)
https://your.icingahost.tld/monitoring/list/services?_service_production_level=&modifyFilter=1

**Comment by K0nne** [comment] 2020-02-26 07:17
We are doing the same thing. To add those variables we rely heavyly on templates.

**Comment by nilmerg** [comment] 2020-02-26 08:26
This is unfortunately a long-standing issue. We currently have no way to express such a filter in our filter syntax. There's #1740 for this.

Though if these variables only contain digits you may succeed with a filter like this: `_host_production_level>0`

**Comment by nilmerg** [comment] 2020-02-26 08:32
Wait, I've actually meant `_host_production_value<=0`, though this also won't work...

Soo, no, there's currently no way to accomplish this with Icinga Web 2. Maybe Icinga 2's API allows this?

**Comment by nilmerg** [comment] 2020-04-21 07:42
Duplicate of #1740. Closing.

**Closed by nilmerg** 2020-04-21 07:42 UTC
