### ISSUE TITLE
Add extension to downloaded CSV file

### ISSUE THREAD

**Issue by KAMI911** [Icinga/icingaweb2#3131] opened 2017-11-22 10:35 UTC
## Expected Behavior
The downloaded CSV file should have csv extension, for example services.csv.

## Current Behavior
For example if I download a CSV file via down arrow I got file name like services. 

## Steps to Reproduce (for bugs)
1. Select a list, for example Service Problems
2. Click on down arrow and select CSV
3. The file save dialog shows services filename instead of services.csv

## Your Environment
Icingaweb2 version 2.4.2 installed from repository to CentOS 7.

**Comment by lippserd** [comment] 2017-11-22 10:39
Hi,

Thanks for the report. This has been fixed in the master branch and will be included in our 2.5.0 release which scheduled for next Monday.

I'll link the related issue later.

Cheers,
Eric

**Comment by KAMI911** [comment] 2017-11-22 14:00
Thank you! I am looking forward to test the shiny new version. ;)

**Comment by Al2Klimov** [comment] 2017-11-23 15:01
Closing as a duplicate of #2808

**Closed by Al2Klimov** 2017-11-23 15:01 UTC
Labels: duplicate
