### ISSUE TITLE
"Check now" not working

### ISSUE THREAD

**Issue by verboEse** [Icinga/icingaweb2#4741] opened 2022-03-31 18:16 UTC
## Describe the bug
The button for "check now" below the header (above the line) has no function. The button beside "last check" does work though.

## To Reproduce
Click on "Check now" - nothing happens

## Expected behavior
at the bottom a bar with "Scheduling check ..." should appear and icingaweb should command the API to do the check.

## Screenshots
![Bildschirmfoto 2022-03-31 um 20 15 40](https://user-images.githubusercontent.com/167254/161122819-28aa870e-88fd-4ee3-a926-29a07ff3d547.png)

## Your Environment
![Bildschirmfoto 2022-03-31 um 20 08 49](https://user-images.githubusercontent.com/167254/161122908-e61af2e0-0e6c-4597-94cf-0bbd386ac969.png)

* Web browser used: Safari, Chrome
* Server operating system and version: Linux Debian

**Comment by TheCry** [comment] 2022-04-01 05:52
I've the same problem. Remove acknowledge (left from "Check now") isn't working, too

**Comment by nilmerg** [comment] 2022-04-01 06:54
The update is out a week now and you don't think anyone else has found these very obvious flaws? Sorry.. there were just so much duplicate reports these days -.-

**Comment by nilmerg** [comment] 2022-04-01 06:55
Duplicate of #4711

**Closed by nilmerg** 2022-04-01 06:55 UTC
