### ISSUE TITLE
User Backend throws exception in configuration form

### ISSUE THREAD

**Issue by gianlucapiccolo** [Icinga/icingaweb2#4358] opened 2021-04-21 08:17 UTC
## Describe the bug
If a custom user backend is configured in the authentication.ini, the user backend create/update/delete form throws an exception. For example, if a custom user backend called test-backend is set in the authentication.ini, the following exception is thrown: Invalid backend type "test-backend" provided.

## To Reproduce
1. add the following configuration to the file authentication.ini: 
```
[bug-test]
backend             = "bugtest"
test_field          = "foobar"
```
2. go to `Configuration > Application > Authentication`
3. in the User Backends list, click on the `bug-test` backend row
4. the exception `Invalid backend type "test-backend" provided` is shown

## Expected behavior
The form to configure the user backend should correctly rendered and work.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.8.2
* Web browser used: chrome
* Icinga 2 version used (`icinga2 --version`): r2.11.6-1
* PHP version used (`php --version`): 7.3.11
* Server operating system and version: CentOS Linux release 7.9.2009

**Comment by nilmerg** [comment] 2021-04-21 08:53
Duplicate of #2840.

**Closed by nilmerg** 2021-04-21 08:53 UTC
