### ISSUE TITLE
Problems w/ DST in the time zone detection

### ISSUE THREAD

**Issue by Christiaan-Liebenberg** [Icinga/icingaweb2#2903] opened 2017-07-28 07:51 UTC
Detail of steps attempted. Have recreated this issue on test environment as well:

https://monitoring-portal.org/index.php?thread/41235-icinga-web-2-incorrect-time-displayed-1-hour-ahead/

## Expected Behavior
Expect my browser to display times in my current time zone, however Icinga Web 2 displays all times as 1-hour ahead.  My current timezone is Africa/Johannesburg UTC +2 with no daylight savings

## Current Behavior
All times displayed in the browser are 1-hour ahead of the client machine's time zone and 1-hour ahead of the servers configured time zone. This occurs on any times displayed by Icinga Web 2 for example:

Notification History
Scheduled Downtime
Host / Service History
Etc

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)
1. Install Icinga 2 Core and Icinga Web 2. Specify date.timezone = "Africa/Johannesburg" in relevant php.ini files

2. Create phpdate.php with the below code and place in web servers root directory
    <?php echo date("Y-m-d H:i:s"); ?>

3 Browse to the phpdate.php page from client machine

4 Observe that the date and time generated by phpdate.php match the client machine's date and time

5 Navigate Icinga Web 2 elements as per 'Current Behaviour' and note that times are displayed incorrectly i.e. 1-hour ahead.

6. Changing the date and timezone on the client machine does not affect the times displayed in-browser for Icinga Web 2

## Context
This is only affecting users browsing objects via Icinga Web 2. Stored dates and times in MySQL are reflect the correct dates and times

## Your Environment
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 - 2.4.1
Grafana - 1.1.2

* Version used (`icinga2 --version`):
Version: r2.6.3-1

* Operating System and version:
Distributor ID: Ubuntu
Description: Ubuntu 17.04
Release: 17.04
Codename: zesty

* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog gelf graphite livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql influxdb mainlog notification

* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.6.3-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: sagrndvmmonm01.sagesl.za.adinternal.com
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-host-notification' (in /etc/icinga2/zones.d/- Global-Templates -/Global.Notifications.conf: 4:1-4:51) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'downtime.updates.linux.nigeria' (in /etc/icinga2/zones.d/- Global-Templates -/Global.Downtimes.conf: 21:1-21:64) for type 'ScheduledDowntime' does not match anywhere!
warning/ApplyRule: Apply rule 'downtime.backups' (in /etc/icinga2/zones.d/- Global-Templates -/Global.Downtimes.conf: 38:1-38:53) for type 'ScheduledDowntime' does not match anywhere!
warning/ApplyRule: Apply rule 'powershell_test' (in /etc/icinga2/zones.d/- Global-Templates -/Global.Service.Checks.Test.conf: 4:1-4:31) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule 'Procs' (in /etc/icinga2/zones.d/- Global-Templates -/Global.Service.Checks.Test.conf: 15:1-15:21) for type 'Service' does not match anywhere!
warning/ApplyRule: Apply rule '' (in /etc/icinga2/zones.d/- Global-Templates -/Global.Service.Checks.Windows.conf: 40:1-40:66) for type 'Service' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 130 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 73 Endpoints.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 255 Notifications.
information/ConfigItem: Instantiated 206 CheckCommands.
information/ConfigItem: Instantiated 2 Downtimes.
information/ConfigItem: Instantiated 129 Hosts.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 15 HostGroups.
information/ConfigItem: Instantiated 22 UserGroups.
information/ConfigItem: Instantiated 30 Users.
information/ConfigItem: Instantiated 704 Services.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 10 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 InfluxdbWriter.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lippserd** [comment] 2017-07-28 08:24
Hi again,

What does your preferences page say about your current time zone? This should be something like `Browser (...)`.

**Comment by Christiaan-Liebenberg** [comment] 2017-07-28 09:15
Hi lippserd, I didn't realize there were user-configurable preferences per login!

Found "Your Current Timezone" under Icinga Web 2 -> User Account Name -> My Account -> Preferences -> Your Current Timezone *

This is configurable. I changed this to Africa/Johannesburg and now all the times are displaying correctly. 
However, this may still be a small-bug. Is Icinga Web 2 supposed to read this timezone from the users' browser? According to the drop-down, it picks up my browser time-zone incorrectly as:

Browser (Europe/Helsinki)

Am happy that it is displaying the correct times now though. Will update the the forum as well

**Comment by lippserd** [comment] 2017-07-28 09:23
Could you please switch the time zone back to browser, destroy the icingaweb2-tzo cookie and reload Icinga Web 2. This will rerun the time zone detection and recreate the cookie. Does this change anything? Have you been in another time zone in the past weeks?

**Comment by Christiaan-Liebenberg** [comment] 2017-07-28 09:39
Ok, 

I set the time-zone back to browser in Icinga Web 2 and exit. 

I am using Chrome Version 60.0.3112.78. In Chrome, I navigate to Settings -> Advanced -> Content Settings -> Cookies -> Search for Ici -> And delete the Icinga cookie I find. If I go into details for this cookie, I see it says icingaweb2-tzo.

I quit Chrome and re-navigate to my Icinga Web 2, under Preferences, I see it still says Europe/Helsinki.
I ask a colleague (on their machine) to navigate to his preferences and they also reflect as Europe/Helsinki.

Neither of us have travelled to alternate time-zones

**Comment by lippserd** [comment] 2017-07-28 09:49
Could please tell me the contents of the cookie?

**Comment by Christiaan-Liebenberg** [comment] 2017-07-28 10:00
![image](https://user-images.githubusercontent.com/26408315/28712524-c4d9f2cc-738b-11e7-842a-5ef2ceb195f7.png)

**Comment by lippserd** [comment] 2017-09-21 09:25
Hi,

Thanks again for your help. The problem is that DST is not taken into account correctly when detecting the time zone.

Best regards,
Eric

**Comment by lippserd** [comment] 2018-01-17 11:28
@Al2Klimov Please evaluate whether and how this could be fixed.

**Comment by Al2Klimov** [comment] 2018-01-17 17:43
@lippserd I'm afraid every gov cooks their own soup here. E.g. Russia (AFAIK) had DST some time, then they've dropped it *while in DST* and then (after some years having DST the whole year) they re-introduced it. (Congrats! Not!) And time zones overlap w/ different states. (E.g. Russia, Mongolia, China) Even if we locate the user, we'd need an always-up-to-date data source for the states' borders. (You know... Alaska – USA, Tibet – China, Krim – Russia, ...) ... and their DST policies.

**Comment by Al2Klimov** [comment] 2018-01-18 14:38
As discussed w/ @lippserd (offline):

Johannesburg and Helsinki have the same wall clock time. PHP just picks the first City (or a random one). Actually a timezone is a set of Cities.

**Comment by Al2Klimov** [comment] 2018-01-18 15:35
As discussed w/ @lippserd (offline):

Stalled until we have a good idea how to solve this.

**Comment by Al2Klimov** [comment] 2018-01-18 15:38
Note:

PHP does *not* automatically convert the displayed time depending on time + zone + DST, e.g:

```php
var_dump(DateTime::createFromFormat('U',1521849723,new DateTimeZone('Europe/Berlin')));
var_dump(DateTime::createFromFormat('U',1521849723+86400*2,new DateTimeZone('Europe/Berlin')));
```

**Comment by mtdeguzis** [comment] 2018-04-07 14:37
I believe I am hitting this as well. When setting up a recurring DT. not sure I understand. Since we are UTC-4 right now for America/NY, asking for 14:00 should have been 18:00 UTC in downtimes.conf, but I had to use: sunday = "19:00-22:00" to achieve our sunday DT for 14:00 localtime. I am UTC-4 right now as the server time is 14:17 and local is 10:17

![image](https://user-images.githubusercontent.com/27829577/38456183-819ab84e-3a4f-11e8-8e5b-ecdfd0e8035d.png)

I use director, but I know recurring DTs cannot be set with director yet.

**Comment by mtdeguzis** [comment] 2018-04-07 16:34
Hmm, if someone can confirm if this is the same bug here?

```
This fixed host downtime has been scheduled to start on 2018-04-08 at 15:00:00 and to end on 2018-04-08 at 18:00:00.
```
When the downtime list shows "starts in 1 d 2 hrs"
Which would be the 14:00 my time that I was targeting.

**Comment by Al2Klimov** [comment] 2018-04-09 07:32
## A tip to all of you

... who just want a correct dates/times to be displayed:

1. Just (re)set "Your Current Timezone" to "Browser (...)" (see [the screenshot above](https://github.com/Icinga/icingaweb2/issues/2903#issuecomment-379473968) for where it is).
2. Don't be confused because of a "wrong timezone" name.

AFAIK "Browser (...)" will just copy your timezone offset (including DST) from +00:00/UTC from your computer's time.

**Comment by lippserd** [comment] 2018-11-16 08:16
I'll close this in favor of #3607 which has a pending PR open which should fix this problem.

**Closed by lippserd** 2018-11-16 08:16 UTC
Labels: bug, stalled
