### ISSUE TITLE
"Check Now" button on top doesn't work

### ISSUE THREAD

**Issue by thrashiii** [Icinga/icingaweb2#4722] opened 2022-03-24 19:38 UTC
## Describe the bug
Since the new update the "check now" button in hosts and services on top has no function. The "check now" button in topic "Check execution" works as usual.

## Screenshots
![check_now](https://user-images.githubusercontent.com/92159500/159996210-01b20ebb-35d8-48af-b298-ee11be07c965.JPG)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.10.0
* Web browser used: Chrome and Firefox
* Icinga 2 version used (`icinga2 --version`):  r2.13.2-1
* PHP version used (`php --version`):  8.0.17
* Server operating system and version:  debian 10.11

**Comment by lippserd** [comment] 2022-03-24 20:04
Hi,

Thanks for the report. This is a duplicate of #4711.

Cheers,
Eric

**Closed by lippserd** 2022-03-24 20:04 UTC
