### ISSUE TITLE
Error when acknowledging in icingaweb2 after updating icinga2 to v2.7

### ISSUE THREAD

**Issue by BirkirFreyr** [Icinga/icingaweb2#2937] opened 2017-09-01 11:45 UTC
icinga2: Can't send external Icinga command: 409 Acknowledgement 'expiry' timestamp must be in the future for object host.domain.com!Hostalive.

#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/AcknowledgeProblemCommandForm.php(159): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\AcknowledgeProblemCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1152): Icinga\Module\Monitoring\Forms\Command\Object\AcknowledgeProblemCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(129): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(77): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->handleCommandForm(Object(Icinga\Module\Monitoring\Forms\Command\Object\AcknowledgeProblemCommandForm))
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->acknowledgeProblemAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('acknowledgeProb...')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}

## Expected Behavior

Timeless acknowledgement for service. (no expiry time)

## Current Behavior

Use expiry time is unchecked but the interface seems to send the acknowledgement command as if it is checked and fails since no time is specified.

## Steps to Reproduce (for bugs)

1. Open icingaweb2
2. Acknowledge a service (Haven't tested for host)
3. Fail.
4.

## Your Environment

* Icinga Web 2 version and modules (System - About): v2.4.1, director 1.3.1, grafana 1.1.7, monitoring 2.4.1
* Version used (`icinga2 --version`): 2.7 (started after updating 2.6.3 -> 2.7)
* Operating System and version: Debian 8.9 with latest updates as of yesterday.
* Enabled features (`icinga2 feature list`): api checker ido-pgsql influxdb livestatus mainlog notification
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

I have tested running an api acknowledgement from command line without expiry time and that worked, so this is an icingaweb2 and not an icinga2 bug.
Icingaweb2 uses API (not command pipe)

**Comment by dnsmichi** [comment] 2017-09-04 08:12
Duplicate of #2911

**Closed by dnsmichi** 2017-09-04 08:12 UTC
Labels: duplicate
