### ISSUE TITLE
Optimize UI for use on mobile devices

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#4095] opened 2020-03-03 15:55 UTC
I developed some ideas for optimising the mobile Ui.

Measures include:
* Redesigning the mobile menu
** Leverage an app like bottom tab bar displaying max 5 main navigation items
** The complete menu is obscured behind a "More …" tab
** Reveal level-2 menu as flyout when tapping Menu Tab
* Increase size of standard touch targets, e.g. tabs in current tab bar
* Hide controls and make them accessible by overscrolling upwards
* Hide object detail actions and make them accessible via a floating action button

![Artboard](https://user-images.githubusercontent.com/6977434/77626497-c06cbe00-6f45-11ea-8ccb-21728b3b366f.jpg)

**Comment by nilmerg** [comment] 2022-03-09 08:14
Duplicate of #4649

**Closed by nilmerg** 2022-03-09 08:14 UTC
Labels: enhancement, area/ui
