### ISSUE TITLE
AND filter does not work with multiple filters

### ISSUE THREAD

**Issue by benkeil** [Icinga/icingaweb2#3469] opened 2018-06-05 14:58 UTC
My hosts are in multiple host groups, for example in `production` and `databases`. Now I want to see hosts which are in these two host groups.

## Expected Behavior
I see only production databases.

## Current Behavior
I see nothing

## Steps to Reproduce (for bugs)
1. Create 2 host groups 
2. Create a host and add it to these two host groups
3. Go to `overview`->`hosts` and filter for these two host group names

## Your Environment

```
Icinga Web 2 Version
2.5.3
Git Commit
ca7e886b820f0145999fdf7377f5c4132301eada
Git Commit Datum
2018-04-27
```

**Comment by lippserd** [comment] 2018-06-20 14:39
Hi,

Thanks for the report. I'll close this as duplicate of #2934.

Cheers,
Eric

**Closed by lippserd** 2018-06-20 14:39 UTC
