### ISSUE TITLE
icingaweb2 translation

### ISSUE THREAD

**Issue by akqopensystems** [Icinga/icingaweb2#4700] opened 2022-03-11 12:15 UTC
## Describe the bug
icingaweb2 translation into german

## To Reproduce
Some checks have multiple outputs. There is also the item "Mehr anzeigen". As soon as you have displayed it and want to display less again. It doesn't show "Weniger zeigen" as expected, but it show "show less".

## Screenshots
![icingaweb2_296_1 (2)](https://user-images.githubusercontent.com/23358770/157864888-bffa3945-ee4c-450a-9e76-a899050ec7f3.PNG)

![icingaweb2_296_2 (2)](https://user-images.githubusercontent.com/23358770/157864958-89b1928d-5b53-4f11-b4be-3a43d94843cc.PNG)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.6
* Web browser used: Firefox 91.6.0.esr, 98.00
* Icinga 2 version used (`icinga2 --version`): 2.12.6
* PHP version used (`php --version`): 7.3.29
* Server operating system and version: RHEL-7.9

**Comment by nilmerg** [comment] 2022-03-11 12:49
Duplicate of #4701

**Closed by nilmerg** 2022-03-11 12:49 UTC
