### ISSUE TITLE
Mass downtime services/devices

### ISSUE THREAD

**Issue by domeniko-gentner** [Icinga/icingaweb2#4890] opened 2022-08-02 09:54 UTC
## Is your feature request related to a problem? Please describe.

I am a network administrator in a company with their own, europe-wide backbone. We use Icinga to monitor our devices. 
When a maintenance is announced by one of our dark fiber or transit providers, I need to downtime certain services to make sure the colleague doing the emergency calls is not getting ringed out of bed for a planned maintenance. 

When these kind of maintenances are announced, I sometimes have to downtime a couple of dozen services or so, depending on which physical route goes down. This includes dwdm devices, repeaters, router interfaces and so on. 

The unfortunate thing here is, I have to set the same date and description for each and everyone of these services. This can be cumbersome and is not very interesting work. It is more of an unwanted chore, especially since you cannot copy the date into the field anymore like you used to be able . 

## Describe the solution you'd like

What I would like is to be able to set the description and timeframe once and then add single services and also whole devices with all services to that downtime event.  This would take a whole lot of work out of the process, since searching is not the issue. 

## Describe alternatives you've considered

I tried using icinga_cli, but I couldn't really figure out how to do that.

**Comment by nilmerg** [comment] 2022-08-02 13:26
Hi, please have a look here: #2344

As I explained there, this is possible in Icinga DB Web and one of the reasons why we put our efforts in the new database backend.

If you don't plan to switch over yet, I'd recommend to utilize the Icinga 2 API directly to perform such bulk operations.

**Comment by nilmerg** [comment] 2022-08-02 13:26
Duplicate of #2344

**Closed by nilmerg** 2022-08-02 13:26 UTC
