### ISSUE TITLE
Schedule downtimes for host/servicegroups

### ISSUE THREAD

**Issue by EmmaTinten** [Icinga/icingaweb2#4541] opened 2021-09-22 08:33 UTC
## Describe the solution you'd like
When selecting a Hostgroup/Servicegroup in the WebUI a simple Button / Link should be available which allows me to schedule a downtime for all contents of the corresponding group. I don't want to select e.g. all 7000 hosts within the group.

**Comment by nilmerg** [comment] 2021-09-22 08:40
Duplicate of #2344

**Closed by nilmerg** 2021-09-22 08:40 UTC
