### ISSUE TITLE
CSV exports have , as an hardcoded delimiter

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2#2809] opened 2017-04-06 17:20 UTC
When exporting stuff via Icingaweb2 and creating CSV files, the crafted CSV uses "," as field delimiters.
This is fine for most folks, but some would prefer other chars (e.g. ";" or <TAB>).

I noticed that the delimiter is hard coded within Csv.php:

```
cat /usr/share/php/Icinga/File/Csv.php
[...]
public function __toString()
    {
        $first = true;
        $csv = '';
        foreach ($this->query as $row) {
            if ($first) {
                $csv .= implode(',', array_keys((array) $row)) . "\r\n";
                $first = false;
            }
            $out = array();
            foreach ($row as & $val) {
                $out[] = '"' . $val . '"';
            }
            $csv .= implode(',', $out) . "\r\n";
        }
[...]
```

In a perfect world, one would be able to configure the delimiter :-)

**Comment by rajo** [comment] 2017-04-26 20:18
see #2513

**Comment by lippserd** [comment] 2017-09-22 08:44
Hi,

Thanks for the report. I close this as duplicate of #2513.

Best regards,
Eric

**Closed by lippserd** 2017-09-22 08:44 UTC
