### ISSUE TITLE
Better Error Naming

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2#3303] opened 2018-01-23 13:44 UTC
Error Return Codes could be better represented in the GUI

Example:
Due to manually creating Dashboards in /etc/icingaweb2/dashboards/admin/dashboard.ini

[Current Incidents.Türme_xyz’s]
url = Türme_xyz’s
title = Türme_xyz’s

Missing quotes will lead to the following error screen.
See Screenshot

![error_screen](https://user-images.githubusercontent.com/7203835/35278923-c6102b50-004b-11e8-91da-35d70a1898d5.png)

![error1](https://user-images.githubusercontent.com/7203835/35279839-917a638a-004e-11e8-8255-db90cbfa4626.jpg)

With an for non technical users not understandable error screen with the following hint "How to solve it". 

## Expected Behavior
More simplified error output like "Missing Quotes! in url & title Field"

## Current Behavior
Cryptic framework error message as seen in screenshot

## Possible Solution
Better and more precise error handling/return output with more simplified error reasons.
 
## Steps to Reproduce (for bugs)
Simply remove Quotes in dashboard.ini

## Your Environment

![error2](https://user-images.githubusercontent.com/7203835/35279856-9c33067e-004e-11e8-90f8-0cfa61eb6fac.jpg)

* Version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.6.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version: Centos 7.4
* Enabled features (`icinga2 feature list`): 
Disabled features: compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`):
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: localhost.localdomain
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 2 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 12 Notifications.
information/ConfigItem: Instantiated 209 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 11 Services.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by Al2Klimov** [comment] 2018-01-25 15:48
Closing as a duplicate of #3252

**Closed by Al2Klimov** 2018-01-25 15:48 UTC
