### ISSUE TITLE
to many menu entries hide dashboard settings

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4625] opened 2021-12-14 11:38 UTC
## Describe the bug
to many menu entries hide dashboard settings
<img width="480" alt="2021-12-14 12_31_27-Fileservices Monitoring-v9-20211213_100653 docx - Word" src="https://user-images.githubusercontent.com/29682206/145990665-d328a639-e063-4c83-920a-38bba1c747be.png">

<img width="317" alt="2021-12-14 12_31_49-_WIN10_ auf _LAPTOP-C30TH6JK_ - Verbindung mit virtuellen Computern" src="https://user-images.githubusercontent.com/29682206/145990705-e3b220eb-1b1a-467c-a036-e25e5efa6534.png">

## To Reproduce
Add more MenuItems or resize window

## Expected behavior
The Add to Dashboard toggle button should be persistent

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.8.3 - 2.9.3
* Web browser used: Chrome, Firefox

## Additional context
Quickfix:
Add to configuration.php
    $this->menuSection('Configuration')->add($this->translate('Dashboard Settings'))->setUrl('dashboard/settings')->setPriority(10);
    $this->menuSection('Configuration')->add($this->translate('Add Dashlet'))->setUrl('dashboard/new-dashlet')->setPriority(10);

**Comment by nilmerg** [comment] 2021-12-14 14:06
Duplicate of #3461

**Closed by nilmerg** 2021-12-14 14:06 UTC
