### ISSUE TITLE
Icingaweb2 2.6.2 LDAP auth issue

### ISSUE THREAD

**Issue by junglistikal** [Icinga/icingaweb2#3729] opened 2019-03-26 14:58 UTC
LDAP auth broke after upgrade from 2.6.1 to 2.6.2

```
2019-03-26T15:58:44+02:00 - ERROR - Icinga\Exception\AuthenticationException in 
/usr/share/php/Icinga/Authentication/User/LdapUserBackend.php:417 with message: 
Failed to authenticate user "some_user" against backend "auth_ad0".
An exception was thrown: <- Icinga\Protocol\Ldap\LdapException in 
/usr/share/php/Icinga/Protocol/Ldap/LdapConnection.php:346 
with message: LDAP bind (DOMAIN\\USER / ***) to domain-controller.example.com 
with default port 389 failed: Invalid credentials
```

## Expected Behavior

Users should log in to Web UI.

## Current Behavior

Users cannot log in to Web UI.

## Steps to Reproduce (for bugs)

1. Upgrade from 2.6.1 to 2.6.2

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.2 with monitoring
* Version used (`icinga2 --version`): 2.10.4
* Operating System and version: RHEL7
* Enabled features (`icinga2 feature list`): api checker command mainlog notification
* Config validation (`icinga2 daemon -C`): All good
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.
* resources.ini: 
```
[ad0]
type      = ldap
hostname  = domain-controller.example.com
port      = 389
root_dn   = "dc=example,dc=com"
bind_dn   = "DOMAIN\\USER"
bind_pw   = "password"

[icingaweb2]
type = "db"
db = "mysql"
host = "localhost"
port = ""
dbname = "icingaweb2"
username = "icingaweb2"
password = "password"
charset = ""
persistent = "0"
```
* groups.ini:
```
[icingaweb2]
backend = "db"
resource = "icingaweb2"

[auth_ad0]
backend  = "msldap"
resource = "ad0"
```
* authentication.ini:
```
[icingaweb2]
backend = "db"
resource = "icingaweb2"

[auth_ad0]
backend  = "msldap"
resource = "ad0"
```

**Comment by nilmerg** [comment] 2019-03-28 07:46
Hi,

you may try the current master. The issue should be solved there.

Closing as duplicate of #3648.

**Closed by nilmerg** 2019-03-28 07:46 UTC
