### ISSUE TITLE
Tiles in dashboard not clickable

### ISSUE THREAD

**Issue by verboEse** [Icinga/icingaweb2#4740] opened 2022-03-31 18:12 UTC
## Describe the bug
Tiles in dashboard are no longer clickable; expansion of marked item is not possible.
The _links_ though (to the service or host) still work.

## To Reproduce
* Open the dashboard
* try to click into a free space on a service/host tile or e. g. on the non-linked text

## Expected behavior
* the second tab opens with the selected service/host
* you would be able to select multiple items/tiles

## Screenshots
![Icinga-bug](https://user-images.githubusercontent.com/167254/161121559-f41e7852-7991-420e-adfe-e2ca4e8cf8a6.png)

## Your Environment
![Bildschirmfoto 2022-03-31 um 20 08 49](https://user-images.githubusercontent.com/167254/161121730-964837c2-123d-49a2-aea5-259d9e821443.png)

* Web browser used: Safari, Chrome
* Server operating system and version: Linux Debian 11

**Comment by nilmerg** [comment] 2022-04-01 06:56
Duplicate of #4710

**Closed by nilmerg** 2022-04-01 06:56 UTC
