### ISSUE TITLE
clicking service details - browser frozen

### ISSUE THREAD

**Issue by nick4me** [Icinga/icingaweb2#2702] opened 2017-01-27 09:21 UTC
Hello,

Clicking on a nwc_health service to see the details the browser is nearly completely frozen

http://1.2.3.4/icingaweb2/dashboard#!/icingaweb2/monitoring/service/show?host=HOST&service=nwc_health

Using the browser's developer console it looks like the network requests are done fast. It looks like there is a problem with the java script.

The given HOST has about 200 network interfaces. Hence there is a bigger check result output
as well as about 2 * 200 performance values (in / out for each network interface).

**Comment by dnsmichi** [comment] 2017-01-27 09:38
Can you provide a screenshot and the output and perfdata strings?

**Comment by Simkimdm** [comment] 2017-05-16 11:31
Hi,
i have the same issue:
Here is a Graph 
![grafik](https://cloud.githubusercontent.com/assets/26118956/26103838/93a28e50-3a3b-11e7-8d47-669f00652dad.png)

and some example from the perfdata strings (I deleted around 3/4 from the output):
'FastEthernet1_usage_in'=0.00%;80;90;0;100 'FastEthernet1_usage_out'=0.00%;80;90;0;100 'FastEthernet1_traffic_in'=98.52;800000000;900000000;0;1000000000 'FastEthernet1_traffic_out'=318.40;800000000;900000000;0;1000000000 'FastEthernet1_errors_in'=0;1;10;; 'FastEthernet1_errors_out'=0;1;10;; 'FastEthernet1_discards_in'=0;1;10;; 'FastEthernet1_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/1_usage_in'=0.01%;80;90;0;100 'TenGigabitEthernet1/1/1_usage_out'=0.05%;80;90;0;100 'TenGigabitEthernet1/1/1_traffic_in'=124480.28;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/1_traffic_out'=497206.73;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/1_errors_in'=0;1;10;; 'TenGigabitEthernet1/1/1_errors_out'=0;1;10;; 'TenGigabitEthernet1/1/1_discards_in'=0;1;10;; 'TenGigabitEthernet1/1/1_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/3_usage_in'=0.01%;80;90;0;100 'TenGigabitEthernet1/1/3_usage_out'=0.05%;80;90;0;100 'TenGigabitEthernet1/1/3_traffic_in'=139473.15;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/3_traffic_out'=481577.55;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/3_errors_in'=0;1;10;; 'TenGigabitEthernet1/1/3_errors_out'=0;1;10;; 'TenGigabitEthernet1/1/3_discards_in'=0;1;10;; 'TenGigabitEthernet1/1/3_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/5_usage_in'=0.00%;80;90;0;100 'TenGigabitEthernet1/1/5_usage_out'=0.05%;80;90;0;100 'TenGigabitEthernet1/1/5_traffic_in'=5893.84;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/5_traffic_out'=501210.90;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/5_errors_in'=0;1;10;; 'TenGigabitEthernet1/1/5_errors_out'=0;1;10;; 'TenGigabitEthernet1/1/5_discards_in'=0;1;10;; 'TenGigabitEthernet1/1/5_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/7_usage_in'=0.00%;80;90;0;100 'TenGigabitEthernet1/1/7_usage_out'=0.02%;80;90;0;100 'TenGigabitEthernet1/1/7_traffic_in'=20.43;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/7_traffic_out'=151214.44;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/7_errors_in'=0;1;10;; 'TenGigabitEthernet1/1/7_errors_out'=0;1;10;; 'TenGigabitEthernet1/1/7_discards_in'=0;1;10;; 'TenGigabitEthernet1/1/7_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/9_usage_in'=0.00%;80;90;0;100 'TenGigabitEthernet1/1/9_usage_out'=0.05%;80;90;0;100 'TenGigabitEthernet1/1/9_traffic_in'=3466.57;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/9_traffic_out'=492813.13;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/9_errors_in'=0;1;10;; 'TenGigabitEthernet1/1/9_errors_out'=0;1;10;; 'TenGigabitEthernet1/1/9_discards_in'=0;1;10;; 'TenGigabitEthernet1/1/9_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/11_usage_in'=0.01%;80;90;0;100 'TenGigabitEthernet1/1/11_usage_out'=0.02%;80;90;0;100 'TenGigabitEthernet1/1/11_traffic_in'=144112.61;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/11_traffic_out'=150434.08;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/11_errors_in'=0;1;10;; 'TenGigabitEthernet1/1/11_errors_out'=0;1;10;; 'TenGigabitEthernet1/1/11_discards_in'=0;1;10;; 'TenGigabitEthernet1/1/11_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/13_usage_in'=0.09%;80;90;0;100 'TenGigabitEthernet1/1/13_usage_out'=0.05%;80;90;0;100 'TenGigabitEthernet1/1/13_traffic_in'=860442.46;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/13_traffic_out'=517935.76;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/13_errors_in'=0;1;10;; 'TenGigabitEthernet1/1/13_errors_out'=0;1;10;; 'TenGigabitEthernet1/1/13_discards_in'=0;1;10;; 'TenGigabitEthernet1/1/13_discards_out'=0;1;10;; 'TenGigabitEthernet1/1/14_usage_in'=0.00%;80;90;0;100 'TenGigabitEthernet1/1/14_usage_out'=0.00%;80;90;0;100 'TenGigabitEthernet1/1/14_traffic_in'=92.24;800000000;900000000;0;1000000000 'TenGigabitEthernet1/1/14_traffic_out'=44645.29;800000000;900000000;0;1000000000  ...

**Comment by lippserd** [comment] 2017-09-21 14:44
Hi,

Thanks for the information. I close this as duplicate of #2894.

Best regards,
Eric

**Closed by lippserd** 2017-09-21 14:44 UTC
Labels: feedback
