### ISSUE TITLE
Redesign the user menu item

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#4096] opened 2020-03-04 09:12 UTC
Here are some ideas for enhancing the user menu item.

* The user menu is moved to the bottom
* The level-2 flyout can contain additional elements, like an environment switcher if applicable or the current Icinga Web node
* The logout button can optionally be placed in the level-1 nav item
* Another option is to print the current node name above the user menu

![Navigation](https://user-images.githubusercontent.com/6977434/77559074-011ff500-6ebc-11ea-91ad-3e6a02172da3.jpg)

**Comment by flourish86** [comment] 2020-03-25 16:27
We also discussed to have a Notification Center integrated.

![Nofications](https://user-images.githubusercontent.com/6977434/77560519-e189cc00-6ebd-11ea-818f-657c0f4d30b7.jpg)

**Comment by nilmerg** [comment] 2022-03-09 08:13
Duplicate of #4651

**Closed by nilmerg** 2022-03-09 08:13 UTC
Labels: enhancement, area/ui
