### ISSUE TITLE
Repaint issues

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#4101] opened 2020-03-10 08:28 UTC
## Describe the bug
Repaint operations must be reduced to the absolute minimum. The current master wastes much more resources than Icinga Web 2.7.3

### Icinga Web 2.7.3

* Auto-Refreshing the right column in Web 2.7.3 repaints just the affected elements in the right column
* A refresh in the left column repaints the main area

### Current Master

* The whole layout (including the menu) repaints even when only the right column is refreshed
* In addition to this, I experienced a whole repaint every single second (without any related XHR request taking place)

## How to reproduce this

Use DevTools and watch how the different versions repaint the UI.

**Comment by nilmerg** [comment] 2020-05-13 09:40
Duplicate of #3683

**Closed by nilmerg** 2020-05-13 09:40 UTC
Labels: area/ui, bug
