### ISSUE TITLE
Custom host vars works fails on servicegroup filter

### ISSUE THREAD

**Issue by firatalkis** [Icinga/icingaweb2#3984] opened 2019-10-18 12:05 UTC
Hello,

when I add custom host variable filter on servicegroup then getting following error.

IcingaWeb2 version : 2.7.2

![image](https://user-images.githubusercontent.com/42132281/67092607-58f15c00-f1b8-11e9-98dc-2b19dea0c75b.png)

**Comment by dnsmichi** [comment] 2019-10-18 12:25
Duplicate of #3983

**Comment by nilmerg** [comment] 2019-10-18 12:44
Hi, there's already a v2.7.3 exactly due to this issue. Just update again and this is solved.

**Closed by nilmerg** 2019-10-18 12:44 UTC

**Comment by firatalkis** [comment] 2019-10-18 13:16
@nilmerg thanks.
