### ISSUE TITLE
Fast clicks in IcingaWeb2 create huge amounts of MySQL tempfiles

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2#3635] opened 2018-11-26 15:45 UTC
## Current Behavior
If you click fast enough on the right icingaweb2 menu entries you can create large amounts of myql tempfiles to fill 20 gb of diskspace within a few minutes. With this one can ddos Icinga2.

## Steps to Reproduce (for bugs)
When I click on the eventgrid it takes about 30 sec to load the page. During this time Icinga2 creates ~4 GB mysql tempfiles. If some users are impatient and click a few times between eventgrid and eventhistory, because the ui seems unresponsive, this triggers the creation of 20 gb tempfiles and more within 3 minutes. I made a "watch la -lah" and the used diskspace increased 1-2 gb per 2 seconds. If the tempdir reaches its limit this happens:

![26-11-_2018_15-27-24](https://user-images.githubusercontent.com/34264690/49023077-a9259100-f196-11e8-9c8d-e36086670fdb.png)

![26-11-_2018_15-27-14](https://user-images.githubusercontent.com/34264690/49023046-9a3ede80-f196-11e8-8abb-b1263d3bbd5a.png)

## Your Environment
* Icinga Web 2 version and modules (System - About):

Icinga Web 2 Version
    2.6.0
Git Commit
    cfe6c7b06587189b3ef688183cacd32594db071a
Git Commit Datum
    2018-07-19
Copyright
    © 2013-2018 Das Icinga Projekt 

Geladene Module
Name 	Version
businessprocess 	2.1.0
monitoring 	2.6.0
pnp 	1.1.0 

* Version used (`icinga2 --version`):

Icinga Web 2 Version
    2.6.0
Git Commit
    cfe6c7b06587189b3ef688183cacd32594db071a
Git Commit Datum
    2018-07-19
Copyright
    © 2013-2018 Das Icinga Projekt 

Geladene Module
Name 	Version
businessprocess 	2.1.0
monitoring 	2.6.0
pnp 	1.1.0 

* Operating System and version:
RHEL 7.4

* Enabled features (`icinga2 feature list`):
 icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb statusdata syslog
Enabled features: api checker ido-mysql mainlog notification perfdata

* Config validation (`icinga2 daemon -C`):
 icinga2 daemon -C
[2018-11-26 16:21:15 +0100] information/cli: Icinga application loader (version: r2.9.1-1)
[2018-11-26 16:21:15 +0100] information/cli: Loading configuration file(s).
[2018-11-26 16:21:16 +0100] information/ConfigItem: Committing config item(s).
[2018-11-26 16:21:16 +0100] information/ApiListener: My API identity: icingamaster01
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 76220 Services.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 60 HostGroups.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 NotificationCommand.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 109609 Notifications.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 18045 Hosts.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 10 Downtimes.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 8 Comments.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 13 Zones.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 18 Endpoints.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 5 ApiUsers.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 254 CheckCommands.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 3 TimePeriods.
[2018-11-26 16:21:24 +0100] information/ConfigItem: Instantiated 1 User.
[2018-11-26 16:21:24 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2018-11-26 16:21:24 +0100] information/cli: Finished validating the configuration file(s).

Its one of those things which only happen in big environments.
I couldn't reproduce it in QS.

Have you any tips how to avoid this problem? The mysql tempdir has 18 gb of unused diskspace at the moment. I could increase it, but if someone knows of this behaviour and clicks long enough ..

**Comment by dnsmichi** [comment] 2018-11-26 15:49
So your database server is running on the same host as Icinga? I would offload that in larger environments, and also analyse what exactly is causing this kind of updates (the exact queries triggered by these "fast clicks").

**Comment by mattef92** [comment] 2019-03-28 16:09
I can confirm the mentioned behavior. 
Icingaweb2 displays the error even when mysql is not on the same machine. 

We could reproduce this error in different ways, only based on opening the event history:
1. In a larger environment the request runs into a php timeout, but the request on the db will continue running. Depending on the data very large mysql tmp table files are created. When the request is sent multiple times the growth is increased due to the parallel requests running for a long time.

2. In a smaller environment
  a) first request returns a result after about 30 seconds. When the request is sent multiple times (like said above due to inpatient users) the disk is filled rapidly with tmp table files
  b) modified the request to run without time filter and after some time only one request managed to create one huge tmp file to fill the disk

The URL which causes the error in our environment can be found here in the code:
https://github.com/Icinga/icingaweb2/blob/184d4afdbdb945fd0ce25c499ea368999a8b8105/modules/monitoring/configuration.php#L248-L253

If i can provide any further information to help, please let me know. Actual workaround is only to kill the executed queries in mysql. This causes mysql to cleanup it's tmp table files.

**Comment by lippserd** [comment] 2019-04-23 11:49
The history related queries are quite slow because the information is clustered over several tables. There are some attempts to fix this though: https://github.com/Icinga/icingaweb2/commits/feature/optimize-ido-mysql
But there is not much going on at the moment because of the Icinga DB development.
I close this issue.

**Closed by lippserd** 2019-04-23 11:49 UTC
