### ISSUE TITLE
Incorrect display of arrays in custom variables section

### ISSUE THREAD

**Issue by danielmoser96** [Icinga/icingaweb2#4481] opened 2021-07-26 09:55 UTC
## Describtion
Since the update of Icingaweb2 to version 2.9.0 the array fields in the custom variable section are not displayed correctly. See screenshot.

## Expected behavior
The values above the array label should appear indented below the label.

## Screenshots:
![image](https://user-images.githubusercontent.com/78567693/126968694-a9fef01c-c0d2-4b38-936e-51ff7377a550.png)

## Environment:

* Icinga Web 2 version and modules (System - About): 2.9.0
1. icinga/icinga-php-library | 0.6.0
2. icinga/icinga-php-thirdparty | 0.10.0
3. director | 1.8.1
4. ipl | v0.5.0
5. reactbundle | 0.9.0
6. monitoring | 2.9.0

* Web browser used: Chrome Version 91
* Icinga 2 version used (`icinga2 --version`): 2.12.5-1
* PHP version used (`php --version`): 7.3.20
* Server operating system and version: Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by nilmerg** [comment] 2021-07-26 10:01
Hi, thanks for your report, but this is a known issue: #4439

**Comment by nilmerg** [comment] 2021-07-26 10:01
Duplicate of #4439

**Closed by nilmerg** 2021-07-26 10:01 UTC
