### ISSUE TITLE
Menu header is repainted on page load

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#3630] opened 2018-11-19 16:42 UTC
## Expected Behavior
No flickering on page load

## Current Behavior
Menu is repainted in an ugly way. This is related to #3629

## Steps to Reproduce (for bugs)
Reload the page, watch.

## Your Environment
It behaves like this since Icinga Web 2.5

**Comment by lippserd** [comment] 2018-11-20 09:17
Fix broke announcements.

**Comment by theFeu** [comment] 2019-06-04 13:31
Will be fixed with #3810

**Comment by nilmerg** [comment] 2019-07-08 10:42
Gets possibly better with #3810. Postponed for v2.8 therefore.

**Comment by nilmerg** [comment] 2020-05-13 10:08
Duplicate of #3683

**Closed by nilmerg** 2020-05-13 10:08 UTC
