### ISSUE TITLE
Allow navigation from parent to children and from child to parents

### ISSUE THREAD

**Issue by wp-perc** [Icinga/icingaweb2#4117] opened 2020-03-31 16:44 UTC
USE CASE:
I'd like to view on each host which are its children and on each child which are its parents. Also, it will be useful to have a fast way to move between them.

EXAMPLE:
On each Host/Service, I'd like to have a section named CHILDREN where all its children are listed, and every name is an http link that allow me to navigate to this specific child.
On Each Host/Service, I'd like to have a section named PARENTS where all its parents are listend, and every name is an http link that allow me to navigate to this specific parent.
This will allow me to rapidly understand dependencies and to move between objects without having to search every time.

I succeeded in allowing navigation from a child to one parent, but is not enough.
What I did:
- create a custom var name host_parent, having the host name of the parent
- add a Host Action named "Go to parent" using the variable above to build an http link
- used a filter on this action to hide it when no parent is defined

But I don;'t think this approach is flexible enough, and can't cover anything about navigating from parent to child.

**Comment by nilmerg** [comment] 2020-04-01 05:33
Hi,

we already have an issue for this.

Duplicate of #2378.

**Closed by nilmerg** 2020-04-01 05:33 UTC
