### ISSUE TITLE
Implement user password reset/create user,roles via icingacli

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2#4187] opened 2020-06-22 15:01 UTC
As for now there is no way to reset a password of the user beside icingaweb. When you have lost your (admin) password you can only modify the database it self and a lot of users are not aware how to do it. This would also help the users who automate a lot of things.

## Describe the solution you'd like
Best would be if icingalic (which can be easly used and only from admins) to create/modify users from the shell. something like 
```
icingacli users password-reset username newpassword
icingcli users add username role password
icingacli roles add rolename (adminrole)
``` 

## Additional context
See community board

**Comment by nilmerg** [comment] 2020-06-23 06:18
Hi,

thanks for the suggestion, though there's already an issue for this. (#3963)

**Comment by nilmerg** [comment] 2020-06-23 06:18
Duplicate of #3963

**Closed by nilmerg** 2020-06-23 06:18 UTC
