### ISSUE TITLE
Sidebar problem counter allow filtering

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2#2795] opened 2017-03-15 13:06 UTC
The Problemcounter on the left side is showing hard and softstates. Would be nice to configure a filter here

**Comment by lippserd** [comment] 2018-01-15 12:48
Hi,

Thanks for the report. We'll consider this for one of our next releases.

Cheers,
Eric

**Comment by SimonHoenscheid** [comment] 2018-01-15 13:10
Thx Eric!

**Comment by MaBauMeBad** [comment] 2018-04-11 13:27
We have also currently need for this. Is it currently possible to change the Filter like for the Daashboards in the configuration.php ?

**Comment by lippserd** [comment] 2018-06-20 14:38
Hi,

No, it's not yet possible. We don't have a schedule for this feature unfortunately.

Best regards,
Eric

**Comment by lippserd** [comment] 2018-06-20 15:11
I close this as duplicate of #3352.

**Closed by lippserd** 2018-06-20 15:11 UTC
Labels: enhancement
