### ISSUE TITLE
Show a more prominent error message, when Icinga 2 is disconnected from IDO

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#2835] opened 2017-05-03 17:05 UTC
Hi,
While we all know relying on the Webinterface to be alarmed about problems in the monitoring backend is not enough and we all have to use Notifications to get aware of such problems, a more prominent error message in Icinga Web 2 might help some users. Especially when the backend is destroyed so thoroughly that it can't send any notifications anymore.
The small red square in the menu is fine but an additional red bar (just like the yellow one showing when commands are sent successfully) could be useful.

(This issue was opened in behalf a customer, so just ask me if you need more information)

Cheers,
Thomas

**Comment by icinga2** [comment] 2017-05-04 06:22
Hi Thomas,
...this is exactly what i mean in our last conversation! i had this problem (backend disconnected)

thanks, Karsten

**Comment by lippserd** [comment] 2017-09-21 13:21
Hi Thomas,

I also think that it is a good idea to show a more prominent error message.

@icinga2 Who are you? I strongly suggest you to rename your account.

Best regards,
Eric

**Comment by ziesemer** [comment] 2018-01-04 03:33
As a corollary to this, please add at least an option to see when each screen was last updated from the server.  This is functionality still missing from the classic UI, where there was a clear "Last Updated" date/timestamp at the top of each screen, along with an "Update in ## seconds" countdown...

Then, when watching this - if the "last updated" time is old, or if the update cycles and doesn't come back with results - then it is easily apparent to anyone watching that something is amiss.

**Comment by dnsmichi** [comment] 2018-01-04 08:34
I don't think that modern web applications should show you an updated counter when the next page refresh happens. That's a moving target always on the screen, and puts away your focus.

Anyhow, it isn't part of the initial request.

**Comment by Thomas-Gelf** [comment] 2018-01-04 08:35
@ziesemer: just stop your webserver and see what happens with your Icinga Web 2 frontend

**Comment by ziesemer** [comment] 2018-01-04 08:51
@Thomas-Gelf - Agreed, understood - but it is still not exactly re-assuring when you can't look and tell that the screens are, in-fact, refreshing - shy of using the browser's developer tools.  (Typical fail-open vs. fail-closed type discussion...)

@dnsmichi - Even if not a counter, just a "last updated" timestamp.  Even if in 8pt text in a page footer.  At least for anything more obtrusive, I wouldn't advocate for adding such details, without making them a user opt-in preference.

I had debated just filing this as a separate request, and then possibly cross-linking it to here - but decided against when #1638 was already closed as a duplicate of this one.  I can still plan on doing so, unless advised otherwise...

**Comment by dnsmichi** [comment] 2018-01-04 08:55
I don't think that the original request and your idea are the same. If you want to discuss about web app features, I'd suggest to join the community channels for getting a better feeling what others think.

**Comment by Thomas-Gelf** [comment] 2018-01-04 11:16
@ziesemer: as @dnsmichi told you, this is far OT and has nothing to do with the original request of this ticket. @widhalmt wants to see a very special error condition shown in a more prominent way.

But please let me still address your concerns:

First, there no need to use developer tools. Isn't the red bar at the bottom bold enough? You don't have much trust into web applications, do you? :laughing: Well, let me explain various possible error conditions and how we're handling them:

* timeout, port blocked, service down, all packet lost in outer space: all these error conditions are handled and show the red bold bar you should have seen once you stopped your web server. We're using a promise guaranteeing that this will happen all the times. If it doesn't, there is either a severe bug in our code, one of the very few libraries we're using - or in your web browser. Sure, there is Murphys law - but still, chances are really low that you might hit such error condition without anyone else reporting this error before.
* 4xx and 5xx: they are usually passed through and are rendered to the GUI. You'll immediately see them. Sometimes they could look ugly - for example when there is a failing proxy sitting in the middle. We might do a better job for some of those with dedicated handlers for some of those (like 503). You can file a dedicated issue for such examples, I'd love to see them implemented
* extremely slow server responses: a slow request starts to gray out the related rendering container after 500ms, it reaches gray color after two seconds

What remains as a potential pitfall is a feature/configuration error. You're allowed disable auto-refresh for your session or in your settings. This is an opt-in feature, mostly used for accessibility reasons. We refresh most parts of the GUI every 10-15 seconds, that could be disturbing when using a screen reader. What could happen is that you accidentally enable this feature, and your front-end stops refreshing. So, there is one more feature request you could open: show that auto-refresh has been disabled i a prominent place in the GUI.

We are currently planning for the next iteration of our web framework, and you can expect more interactivity to flow in. I'd love to ship event-based server side pushing of updates to the browser.  Our session handling will be redesigned to reach this goal, and background jobs for all modules will become a thing. But there will still remain some ping-alike logic in the client part that will be able to inform you once the server fails.

In addition, we want to benefit from new features todays browsers ship for Progressive Web Apps. We'll for example be able to tell you that your phone lost it's Internet connection. Still, we do not want to have one of those super-"modern" bloated slow JS-only front-ends. We'll continue following our pretty conservative and pragmatic way when using new technologies.

All this will result in less traffic, less noise, less overhead, less CPU cycles. There will be less traffic, good for your mobile device. Less requests repainting parts of the UI all the times, so less CPU overhead for your browsing device. Something repainting "last refresh happened 3 seconds ago" all the times contradicts this strategy.

We take Monitoring serious and we want our users to be able to put trust in our application. Icinga should and will tell you when something is wrong. And it shouldn't bother you when everything is fine. An application constantly yelling "I'm still here, I'm alive, I'm still here" does not fit into this picture. When this is what you expect us to do, my conclusion is that there is still not enough trust at your side. Please let me know what we can do to get better here. I'm sure we can get there, even without behaving like a web page from the nineties.

In my believes we already ship a very fast and reliable web application. But we'll not stop here, we can do even better.

Cheers,
Thomas

**Comment by ziesemer** [comment] 2018-01-04 13:27
@Thomas-Gelf - Thank you for all the details, and commitment to taking monitoring seriously.  I didn't mean to start a debate!  I've been using Icinga since its inception, and am very pleased with the overall solution - it has been my go-to- monitoring tool across several organizations.  From my context during that time - it's not that I don't trust web applications or the development here, etc. - but I have seen the things that can and do go unexpectedly.  If just for one other potential use case, a hung browser tab / process could appear no differently than a working one - and would also prevent any of the safeguards mentioned above from indicating otherwise.

If nothing else, I suppose one could create a dashlet that simply returns the time from the server - possibly directly from IDO, if that makes sense.  It could be user-added to a dashboard, and would then refresh along with the rest of the application.

**Comment by Thomas-Gelf** [comment] 2018-01-04 15:06
> I didn't mean to start a debate!

Well... we're living in times where many people are unable to type more than 140 consecutive characters at once. And even those only assisted by auto-completion. Once I went to school, 140 characters was the bare minimum one had to accomplish on average - per minute. 300 characters per minute where necessary to be amongst the fast ones. Different times, I now. Today the biggest and loudest baby wins the "debate". I miss those good old times, where it was still possible to debate based on arguments...

> [..] I have seen the things that can and do go unexpectedly.

Believe me: me too. And I want to catch and handle them. All of them ;-) I'm old enough to understand that this won't be possible, but I still didn't met a realistic case we're unable to catch.

> If just for one other potential use case, a hung browser tab / process [..]

Absolutely true, that's one we wouldn't be able to catch. That's up to the browser or the operating system. Did this ever happen to you? Recently? Using a (more or less) modern browser? In combination with Icinga Web 2? I'm usually REALLY stressing my systems - and this never happens to me. When a browser tab goes wild, the browser either asks me to stop it's scripts, or the browser dies. Or it eats all my resources and takes down the whole operating system down with him. Cannot remember a single (unnoticed) frozen visible tab during the last years. Happens rarely when the whole operating system freezes, but then usually the screen blanks out after a while - so it would be noticed.

> [..] a dashlet that simply returns the time from the server [..]

I'd also love to see a small component showing Server Time (and timezone) next to Browser Time (and timezone). Time difference drifting away should be highlighted. But even with this, you wouldn't immediately notice when the system freezes. Still, it would be a useful component, I like this idea. Such a dashlet would be very easy to implement, please open a dedicated feature request. In addition, it would be nice to have an option allowing those who care to show this all the time in a dedicated place. The only problem is: WHERE should we place it? Very small, below the Icinga logo?

> [..] possibly directly from IDO [..]

Now we're back on track. Lagging/dead IDO should be highlighted immediately. This already happens. But it could be shown in a more prominent way - similar to that red bottom bar. Guess that's what @widhalmt wants to see. As monitoring/IDO is just one module amongst others, a hook allowing modules to show a sticky error unless the problem is going to be resolved would be great. Still unsure of how to implement/provide this in a meaningful and pleasant way.

Since our very first Icinga Web 2 release, every module can provide it's own "health check" in the menu. If we use all of them at a global level too, there could be too much noise: lagging IDO, Director currently unable to deploy, three delayed import jobs, new unhandled host problems... and maybe the main reason for all of this is was just a temporary problem on your central storage device. In such case, all those problems shouldn't clutter the whole screen.

We already handle that specific error (IDO has a problem), it currently pops up as a red badge in the menu. @widhalmt wants this to be shown in a more prominent way, as some people might overlook this. Other people might complain when bothered with this all the times, as their deployment never finishes in two seconds. Satisfy all of them is IMO what this issue is all about.

Very easy to implement. Once we know, how exactly it should behave :laughing:

**Comment by Thomas-Gelf** [comment] 2018-01-04 15:08
@ziesemer: sorry, I edited your comment instead of posting a new one. Restored your original one, sorry for the noise.

**Comment by widhalmt** [comment] 2018-01-04 15:28
> Now we're back on track. Lagging/dead IDO should be highlighted immediately. This already happens. But it could be shown in a more prominent way - similar to that red bottom bar. Guess that's what @widhalmt wants to see.

Yep. That's what this is all about. I'm quite baffled about what I started without having anything big in mind. :-)

BTW: I too think, a debate is a good thing that's one of the few ways to really make some progress. Don't fear debating. But keep it all nice, that's where some fail and spoil the fun for the rest of us.

So I think there is at least one feature request that could be spring from this one. But my original intention was just to make it more easily detectable when the connection between Icinga 2 and the IDO is lost or stale, just as you said, @Thomas-Gelf .

**Comment by widhalmt** [comment] 2018-01-04 15:58
A short note about my message above, because I was asked in a private message: I did not mean that someone in this thread wasn't playing nice. On the contrary, you are debating how it should be done. If anything you're too nice. :smile: 
I should stop posting my opinion about humankind as a whole on a philosophical level when writing into a technical thread. Sorry for the fuzz.

**Closed** 2018-07-10 07:14 UTC
Labels: enhancement
