### ISSUE TITLE
Fine-grained permission management

### ISSUE THREAD

**Issue by tktr** [Icinga/icingaweb2#4200] opened 2020-07-03 14:12 UTC
## Is your feature request related to a problem? Please describe.
With the current permission management implementation, it is not possible to assign roles with different restrictions and different permissions to a single user. Consider the following **roles.ini** file:

`
[web-operator]
permissions = "module/monitoring,monitoring/command/*"
users = "jdoe"
monitoring/filter/objects = "hostgroup_name=grp_web"

[db-viewer]
permissions = "module/monitoring"
users = "jdoe"
monitoring/filter/objects = "hostgroup_name=grp_db"
`

In this scenario, the user **jdoe** will effectively have the **monitoring/command/*,module/monitoring** permission on all hosts which are part of either **grp_db** or **grp_web** which is not intended. 

## Describe the solution you'd like
Permissions should be scoped to the set of hosts matching the filter which would make it possible to define fine-grained roles. In the scenario from above, the user should effectively only have the **module/monitoring** permission on **grp_db**.

**Comment by nilmerg** [comment] 2020-07-06 06:12
Hi,

this is a well known feature request. (#2455) But rest assured, it's something we're planning for the next major release.

**Comment by nilmerg** [comment] 2020-07-06 06:12
Duplicate of #2455

**Closed by nilmerg** 2020-07-06 06:12 UTC
