### ISSUE TITLE
CSS reload bomb (GET /css/icinga.min.css?id=1616668150919)

### ISSUE THREAD

**Issue by mwetterw** [Icinga/icingaweb2#4340] opened 2021-03-29 09:20 UTC
## Describe the bug
The JavaScript code of Icingaweb is generating a storm of **GET /css/icinga.min.css?id=1616668150919**
By storm, I mean thousands of GET per second.
The Icingaweb tab of the browser starts to eat up 100% of the CPU and the whole browser eventually freezes completely.

## To Reproduce
The bug is extremely hard to reproduce, it doesn't happen all the time.
You can open the Console in the browser and trigger this function manually: `window.icinga.ui.reloadCss();`
You can immediately after open the Network console and see if you have more than one GET for the CSS.

## Expected behavior
The CSS is expected to reload itself only if it is proven necessary: for example, when the theme has changed or the CSS file itself has changed.

## Your Environment
* Icinga Web 2 version: **v2.8.2**
* IcingaWeb modules: **monitoring (2.8.2)**
* Web browser used: **Firefox 86.0**
* Icinga 2 version used (`icinga2 --version`): **r2.12.1-1**
* PHP version used (`php --version`): **PHP 7.3.19**
* Server operating system and version: **Debian 10.6**

## Additional context
- We use two masters.
- On each master, an instance of Icinga is installed.
- On each master, an instance of Icingaweb is running behind Nginx
- A loadbalancer provides a unique entry point to our Icingaweb infrastructure.
- Sessions are not shared on a common storage. Each master's PHP will store its session individually, so we use a **source IP based load-balancing** strategy so that during the navigation, a user will always end up on the same Icingaweb.

## Possible cause
It might be related to this quickfix:
https://dev.icinga.com/issues/10957 (#2233)
https://github.com/Icinga/icingaweb2/blob/v2.8.2/library/Icinga/Authentication/Auth.php#L138-L139

## Sum-up of code flow
Here is the summary of the calls between PHP and JS:
- Anytime a user is successfully authenticated,
`Icinga\Authentication\Auth::setAuthenticated()` calls `Icinga\Web\Response::setReloadCss(true)`.
https://github.com/Icinga/icingaweb2/blob/v2.8.2/library/Icinga/Authentication/Auth.php#L139

- When preparing a response in `Icinga\Web\Response`, when `isReloadCss()` property is true, a HTTP Header `X-Icinga-Reload-Css` will be appended to the response.
https://github.com/Icinga/icingaweb2/blob/v2.8.2/library/Icinga/Web/Response.php#L302

- On the client side, the Icinga Javascript loader responsible of all XHR requests will check if any response has the header `X-Icinga-Reload-Css` set. If yes, it will then call `icinga.ui.reloadCss()` JavaScript function.
https://github.com/Icinga/icingaweb2/blob/v2.8.2/public/js/icinga/loader.js#L621

- `icinga.ui.reloadCss()` will get all `<link>` HTML tags and it will prepare new `<link>` tags with a new `href` attribute of
**/css/icinga.min.css?id=DATETIME**
It will then delete the old `<link>` tags and append the new `<link>` tags to the `<head>` node in the DOM.
https://github.com/Icinga/icingaweb2/blob/v2.8.2/public/js/icinga/ui.js#L107

- This effectively makes the browser generate a `GET /css/icinga.min.css?id=DATETIME` request.

Now, it is still unclear for me why sometimes, a storm of those GET is generated. I haven't found the root-cause yet.

**Comment by mwetterw** [comment] 2021-03-29 09:33
Maybe it will be corrected by this patch? :)

https://github.com/Icinga/icingaweb2/commit/930acbdad84460cd8fa22a0726f1b781fb20a984

**Comment by nilmerg** [comment] 2021-03-29 10:35
Hi,

the patch you've referenced only limits when the CSS is reloaded. (Not every time anymore) It doesn't change how the CSS is being reloaded.

However, what you're describing sounds to me like a caching/redirection issue. Or maybe the browser reloads the CSS recursively because the actual CSS reload triggers another one?

Could you please try to provide us with the request/response headers of such a repeated request? I know, that's difficult if the issue isn't easily reproducible and the browser freezes. Maybe you could setup a log on the server or so?

**Comment by nilmerg** [comment] 2022-05-27 12:40
We had no similar reports in the past and here no further feedback has been added. Closing.

**Closed by nilmerg** 2022-05-27 12:40 UTC
Labels: needs-feedback
