### ISSUE TITLE
Add support for removing downtime on host + services

### ISSUE THREAD

**Issue by paladox** [Icinga/icingaweb2#3548] opened 2018-08-03 15:56 UTC
Hi, please could support for removing a downtime on a host + service be supported?

Ie if you were to downtime a host and also clicked "all services" and all child services, could we support being able to remove that downtime?

**Comment by tobiasvdk** [comment] 2018-11-08 16:48
Looks like a duplicate of #3194.

**Comment by lippserd** [comment] 2018-11-16 14:59
I'll close this as duplicate of #3194

**Closed by lippserd** 2018-11-16 14:59 UTC
