### ISSUE TITLE
 isChecked() on null in /usr/share/php/Icinga/Web/Form.php:1231 after update to 2.10

### ISSUE THREAD

**Issue by mphilipps** [Icinga/icingaweb2#4718] opened 2022-03-24 08:59 UTC
hi,
Just updated icingaweb only to be suddenly pesented with an darkmode. I then went into My Account and tried changing my theme back to my old one only to be greeted by this error message:

```
Uncaught Error: Call to a member function isChecked() on null in /usr/share/php/Icinga/Web/Form.php:1231
Stack trace:
#0 /usr/share/icingaweb2/application/forms/PreferenceForm.php(438): Icinga\Web\Form->isSubmitted()
#1 /usr/share/php/Icinga/Web/Form.php(1175): Icinga\Forms\PreferenceForm->isSubmitted()
#2 /usr/share/icingaweb2/application/controllers/AccountController.php(78): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AccountController->indexAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\A
```
![screen02](https://user-images.githubusercontent.com/17722151/159879708-5bd124ac-6c49-4607-a631-5b53a31a2b84.png)

**Comment by mphilipps** [comment] 2022-03-24 09:00
![screen03](https://user-images.githubusercontent.com/17722151/159880097-d4865c1d-f12d-4b6c-b366-d1c5f341f6d0.png)

**Comment by nilmerg** [comment] 2022-03-24 09:15
Hi,

this occurs because you don't have a *User Preference Storage Type* configured. This is [deprecated](https://github.com/Icinga/icingaweb2/blob/master/doc/80-Upgrading.md#upgrading-to-icinga-web-2-29x) since v2.9.0. Please configure a database as *User Preference Storage Type* in the general configuration and this error is gone.

**Comment by nilmerg** [comment] 2022-03-24 09:15
Duplicate of #4618

**Closed by nilmerg** 2022-03-24 09:15 UTC

**Comment by mphilipps** [comment] 2022-03-24 09:21
@nilmerg I have a user preference storage type:

![screen04](https://user-images.githubusercontent.com/17722151/159884030-d15b6963-666e-4856-b4b3-29b994478850.png)

According to the warning and the changelog you linked ini should still work in 2.10.

**Comment by nilmerg** [comment] 2022-03-24 09:24
Yeah, the storage type works fine. For existing configurations, which means existing files can be loaded fine. We just don't plan to fix bugs related to this anymore. Just switch to database and it's fine. There is even a migration script provided to assist you in this. Check the upgrading documentation.

**Comment by mphilipps** [comment] 2022-03-24 09:35
@nilmerg It is not that easy. Currently we write the roles.ini file from our configuration management to ensure that each user has the correct permissions. Can you confirm that roles.ini is not considered a 'User Preference' and is unaffected by the storage type?

**Comment by nilmerg** [comment] 2022-03-24 09:44
Yes, a quote from the upgrading documentation:

> Note that this only applies to user preferences. Other configurations are still stored in .ini files. (https://github.com/Icinga/icingaweb2/issues/3770)

**Comment by mphilipps** [comment] 2022-03-24 11:10
@nilmerg I have tested the ini -> db migration on one host and I don't longer encounter the error when changing themes. However I noticed that my `menu.ini` from `preferences/mphilipps` is not in the db, but instead loaded from the filesystem. Did I do an incomplete migration? Am I running in some mixed mode?

**Comment by nilmerg** [comment] 2022-03-24 11:17
No. Yes. That's still an open issue (#2209)
