### ISSUE TITLE
The 'monitoring/filter/objects' restriction based on 'hostgroup_name' field produce error when accessing some hosts

### ISSUE THREAD

**Issue by slaveeu** [Icinga/icingaweb2#4072] opened 2020-02-10 15:59 UTC
## Describe the bug
The 'monitoring/filter/objects' restriction based on hostgroup_name field
produce below error when accesing some hosts
(error happens when accessing the host that does not belongs to the first hostgroup - alphabetically sorted)  

```
#0 /usr/share/icingaweb2/library/Icinga/Exception/IcingaException.php(41): ReflectionClass->newInstanceArgs(Array)
#1 /usr/share/icingaweb2/library/Icinga/Web/Controller.php(87): Icinga\Exception\IcingaException::create(Array)
#2 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostController.php(33): Icinga\Web\Controller->httpNotFound(String)
#3 /usr/share/icingaweb2/library/Icinga/Web/Controller/ActionController.php(152): Icinga\Module\Monitoring\Controllers\HostController->init()
#4 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/icingaweb2/library/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}
```

## To Reproduce
    Create 3 hostgroups:  testHG1, testHG2 and testHG3
    For each hostgroup create 1 associated host: 
	testH1 - belonging to testHG1
	testH2 - belonging to testHG2
	testH3 - belonging to testHG3
	
	Create a role with the following monitoring/filter/objects filter: _hostgroup_name=testHG*_
        and an user 'test' associated with it.  
	(The filter hostgroup_name=testHG1|hostgroup_name=testHG2|hostgroup_name=testHG3 
         will produce the same behavior )
	
	Login to Icingaweb as 'test' user and try to access the defined hosts
	
	Accesing 'testH1' will work fine, but 'testH2' and 'testH3' will generate an error

    Aditional test: 
	Set the filter to 'hostgroup_name=testHG2|hostgroup_name=testHG3'
    In this case: 
	Accesing 'testH2' will work fine
	Accesing 'testH3' will generate an error

## Expected behavior
All hosts should be accessed succesfully without errors

## Screenshots
![image](https://user-images.githubusercontent.com/51120510/74154715-72a92a00-4c13-11ea-932d-2c177be956bd.png)

## Your Environment
Icinga Web 2 Version 2.7.3
PHP Version 7.1.30
Server operating system and version: RHEL 7

## Additional context
Interesting workarround: 
With the following filter (hostgroup_name=testHG*|host_name=none_existing_host) all hosts can be accessed without this error

**Comment by nilmerg** [comment] 2020-02-17 15:16
Hi,

I can't reproduce this. Please add a few more details and verify that you're really running Icinga Web 2 2.7.3 on the endpoint you're trying this.

Details:
* Icinga 2 version
* Database vendor and version
* Any modules and their versions

**Comment by nilmerg** [comment] 2020-04-07 06:29
Closing due to missing feedback. Please re-open if you deem it necessary.

**Closed by nilmerg** 2020-04-07 06:29 UTC
Labels: needs-feedback
