### ISSUE TITLE
Zend_Db_Statement_Exception Undefined function: 7 FEHLER: Funktion from_unixtime(timestamp without time zone) existiert nicht

### ISSUE THREAD

**Issue by ulfkosack** [Icinga/icingaweb2#4859] opened 2022-07-03 16:44 UTC
## Describe the bug
On menu entry history > event grid the an db error message is shown:

```
Zend_Db_Statement_Exception in /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php:225 with message: SQLSTATE[42883]: Undefined function: 7 FEHLER: Funktion from_unixtime(timestamp without time zone) existiert nicht
LINE 1: SELECT DATE(FROM_UNIXTIME(sth.timestamp)) AS day, SUM(CASE W...
^
HINT: Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufügen., query was: SELECT DATE(FROM_UNIXTIME(sth.timestamp)) AS day, SUM(CASE WHEN sth.state = 2 AND sth.type = 'hard_state' THEN 1 ELSE 0 END) AS cnt_critical_hard FROM (SELECT sh.statehistory_id AS id, ('service') AS object_type, h.display_name AS host_display_name, so.name1 AS host_name, so.name2 AS service_description, s.display_name AS service_display_name, so.name1 AS service_host_name, (CASE WHEN sh.state_type = 1 THEN 'hard_state' ELSE 'soft_state' END) AS type, sh.state_time AS timestamp, sh.object_id, sh.state, (CASE WHEN sh.state_type = 1 THEN sh.output ELSE '[ ' || sh.current_check_attempt || '/' || sh.max_check_attempts || ' ] ' || sh.output END) AS output FROM icinga_statehistory AS sh
INNER JOIN icinga_objects AS so ON so.object_id = sh.object_id AND so.is_active = 1 AND so.objecttype_id = 2
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id
INNER JOIN icinga_hosts AS h ON h.host_object_id = s.host_object_id WHERE (sh.state_time >= '2022-04-03 16:34:33')) AS sth GROUP BY DATE(FROM_UNIXTIME(sth.timestamp)) ORDER BY DATE(FROM_UNIXTIME(sth.timestamp)) DESC
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(304): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Select.php(705): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/php/Icinga/Data/Db/DbConnection.php(102): Zend_Db_Select->query()
#5 /usr/share/php/Icinga/Data/SimpleQuery.php(168): Icinga\Data\Db\DbConnection->query()
#6 /usr/share/icingaweb2/modules/monitoring/application/views/scripts/list/eventgrid.phtml(55): Icinga\Data\SimpleQuery->rewind()
#7 /usr/share/php/Icinga/Web/View.php(235): include(String)
#8 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#16 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#17 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#18 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#19 {main}
```
## To Reproduce
Click on history > event grid

## Expected behavior
Show Data

## Screenshots
![grafik](https://user-images.githubusercontent.com/16068801/177048967-83c43190-36ae-4153-83e4-597980e2ef9d.png)

## Your Environment
Master-Master installation on Debian 11 with Icinga2 and Icingaweb2 on both hosts. PostgreSQL 12 as db server.

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version 	2.11.0
Git Commit 	46998464ea9f9e3c2889d98f9fb6df639d972550
PHP-Version 	7.4.28
Git Commit Datum 	2022-06-30

Geladene Bibliotheken
icinga/icinga-php-library 	0.9.0
icinga/icinga-php-thirdparty 	0.11.0
Geladene Module
director 		1.9.1 	
fileshipper 		1.2.0 	
incubator 		0.17.0 	
ipl 		v0.5.0 	
monitoring 		2.11.0 	
nordlicht 		1.0.0 	
reactbundle 		0.9.0 	
spring 		0.0.1 	
Copyright © 2013-2022 Icinga GmbH

* Web browser used: Firefox 91.11.0 ESR, Google Chrome 103.0.5060.66 
* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

* PHP version used (`php --version`): 7.4.28
* Server operating system and version:
System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.15.35-3-pve
  Architecture: x86_64

## Additional context
After upgrade via apt

`Upgrade: icingacli:amd64 (2.10.1-1.bullseye, 2.11.0-1.bullseye), icingaweb2-common:amd64 (2.10.1-1.bullseye, 2.11.0-1.bullseye), icinga-php-thirdparty:amd64 (0.10.0-2.buster, 0.11.0-1.bullseye), php-icinga:amd64 (2.10.1-1.bullseye, 2.11.0-1.bullseye), icingaweb2:amd64 (2.10.1-1.bullseye, 2.11.0-1.bullseye), icinga-php-library:amd64 (0.8.1-1.bullseye, 0.9.0-1.bullseye), icingaweb2-module-monitoring:amd64 (2.10.1-1.bullseye, 2.11.0-1.bullseye), icingaweb2-module-doc:amd64 (2.10.1-1.bullseye, 2.11.0-1.bullseye)
`

**Comment by nilmerg** [comment] 2022-07-04 07:47
Hi, thanks for the report. This is already tacked here: #4853

**Comment by nilmerg** [comment] 2022-07-04 07:47
Duplicate of #4853

**Closed by nilmerg** 2022-07-04 07:47 UTC
