### ISSUE TITLE
Add new (local) Dashlet fails: The url must not be external

### ISSUE THREAD

**Issue by KZVMV-EDV** [Icinga/icingaweb2#4984] opened 2023-01-16 11:49 UTC
## Describe the bug
I tried to customize my dashboard by simply adding the "hostgroups" to my dashboard.
But whenever I try to save it, i get the following error:
"The url must not be external."

The url itself is definitly **not** external. I have tried the following two URL-patterns:
_http://aaa.bbb.ccc.ddd/icingaweb2/icingadb/hostgroups_
and
_icingadb/hostgroups_

## To Reproduce
1. Go to Overview -> Hostgroups
2. Use the "Add to Dashboard" Option at the far top
3. Enter a title
4. Save

## Expected behavior
Save of the dashlet and showing it on the dashboard.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.11.3
* Web browser used: Firefox 102.6.0esr (64-Bit)
* Icinga 2 version used (`icinga2 --version`): r2.13.6-1
* PHP version used (`php --version`): PHP 7.4.33 
* Server operating system and version: Debian 11 (bullseye)

## Additional context
I tried to debug the problem myself. It seems, that the "scheme" check inside the InternalUrlValidator does not work properly, because the URL Object is not generally build with scheme. 
- Icinga\Web\Form\Validator\InternalUrlValidator
--- Icinga\Web\Url::fromPath

**Comment by nilmerg** [comment] 2023-01-16 12:18
Thanks for the report. Though, it's a known issue: #4970

**Comment by nilmerg** [comment] 2023-01-16 12:19
Duplicate of #4970

**Closed by nilmerg** 2023-01-16 12:19 UTC
