### ISSUE TITLE
If a downtime gets canceled, show who removed it in the history views

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2#3501] opened 2018-07-03 09:58 UTC
## Expected Behavior
While creating a Downtime in Icingaweb2 there is the creator user shown in the History.
When deleting the Downtime with another user that has the appropriate rights this user should be shown as the user who deleted the Downtime

## Current Behavior
When deleted in the History the Downtime still shows the creation user instead of the deletion initiator.
![downtime web2 wrong user](https://user-images.githubusercontent.com/7203835/42213116-41b7e92e-7eb8-11e8-8065-310c151b0ac1.png)

## Possible Solution
Probably re-populate the field value with the correct owner/initiator.

## Steps to Reproduce (for bugs)
1) Create a fresh/blank Icinga2 installation with Icingaweb2.
2) Create downtime object with downtime amount that fulfils it's purpose and create another user that has the rights to delete that downtime.
3) Log out of the downtime creator account. Log into the newly created account.
4) Delete Downtime.
5) Take a look at the History and see that the deletion initiator "owner" is still the creator of that downtime.

## Context
It would be useful if it could be seen who deleted the downtime if it wasn't meant that the Person should do that.

## Your Environment
* Icinga Web 2 version and modules (System - About):
![web2 module version](https://user-images.githubusercontent.com/7203835/42212926-c3412d62-7eb7-11e8-999b-f2b63ee3c62a.png)

* Version used (`icinga2 --version`):
[root@localhost ~]# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-862.3.3.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version:
[root@localhost ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
* Enabled features (`icinga2 feature list`):
[root@localhost ~]# icinga2 feature list
Disabled features: api compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: checker command ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`):
[root@localhost ~]# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.4-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 12 Notifications.
information/ConfigItem: Instantiated 209 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 12 Downtimes.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 11 Services.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

[root@localhost ~]# icinga2 object list --type Endpoint
Object 'localhost.localdomain' of type 'Endpoint':
  % declared in '/etc/icinga2/zones.conf', lines 7:1-7:24
  * __name = "localhost.localdomain"
  * host = "localhost.localdomain"
    % = modified in '/etc/icinga2/zones.conf', lines 8:3-8:17
  * log_duration = 86400
  * name = "localhost.localdomain"
  * package = "_etc"
  * port = "5665"
  * source_location
    * first_column = 1
    * first_line = 7
    * last_column = 24
    * last_line = 7
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "localhost.localdomain" ]
    % = modified in '/etc/icinga2/zones.conf', lines 7:1-7:24
  * type = "Endpoint"
  * zone = ""

[root@localhost ~]# icinga2 object list --type Zone
Object 'director-global' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 36:1-36:29
  * __name = "director-global"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 37:3-37:15
  * name = "director-global"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 36
    * last_column = 29
    * last_line = 36
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "director-global" ]
    % = modified in '/etc/icinga2/zones.conf', lines 36:1-36:29
  * type = "Zone"
  * zone = ""

Object 'global-templates' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 24:1-24:30
  * __name = "global-templates"
  * endpoints = null
  * global = true
    % = modified in '/etc/icinga2/zones.conf', lines 25:3-25:15
  * name = "global-templates"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 24
    * last_column = 30
    * last_line = 24
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "global-templates" ]
    % = modified in '/etc/icinga2/zones.conf', lines 24:1-24:30
  * type = "Zone"
  * zone = ""

Object 'localhost.localdomain' of type 'Zone':
  % declared in '/etc/icinga2/zones.conf', lines 11:1-11:20
  * __name = "localhost.localdomain"
  * endpoints = [ "localhost.localdomain" ]
    % = modified in '/etc/icinga2/zones.conf', lines 12:3-12:26
  * global = false
  * name = "localhost.localdomain"
  * package = "_etc"
  * parent = ""
  * source_location
    * first_column = 1
    * first_line = 11
    * last_column = 20
    * last_line = 11
    * path = "/etc/icinga2/zones.conf"
  * templates = [ "localhost.localdomain" ]
    % = modified in '/etc/icinga2/zones.conf', lines 11:1-11:20
  * type = "Zone"
  * zone = ""

**Comment by lippserd** [comment] 2018-11-19 08:51
Hi,

Thanks for the report. The remove comment command in Icinga 2 does not support setting who removed the comment. So we can't just display who removed it. But I see your point. We think about whether and how to fix this in one of our next releases. When fixing this, I think we should display the reason for downtime end events. If the reason is cancelled by user, we should display who removed it.

Best,
Eric

**Comment by mafri27** [comment] 2020-01-16 16:19
hello,
is there some plan to implement this feature?
best, Martin

**Comment by nilmerg** [comment] 2020-05-20 12:11
This will be part of Icinga 2.12 and Icinga Web 2.8. (by #4155) Though, this will only be visible in Icinga DB Web as the IDO has no notion of who removed what.

**Comment by nilmerg** [comment] 2020-05-20 12:11
Duplicate of #2281

**Closed by nilmerg** 2020-05-20 12:11 UTC
Labels: enhancement, needs-sponsoring
