### ISSUE TITLE
[dev.icinga.com #12462] Icingaweb2 shows twice as many unhandled services

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2526] opened 2016-08-17 09:48 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12462

**Created by MarcusCaepio on 2016-08-17 09:48:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-28 09:04:27 +00:00 (in Redmine)_

---

Hi all,

Icingaweb2 shows twice as many unhandled services as they really are.
E.g. 1 Service Problem is given, it is shown as 2 unhandled Services
See attached screenshot.

Regards,
Marcus

**Attachments**

* [screenshot.PNG](https://dev.icinga.com/attachments/download/3592/screenshot.PNG) MarcusCaepio - _2016-08-17 09:47:24 +00:00_

---

**Relations**:

* relates [#11566](https://dev.icinga.com/issues/11566)

**Comment by nilmerg** [comment] 2018-05-02 07:31
Duplicate of #2822, fixed with #3083 and released as part of [v2.5.0](https://github.com/Icinga/icingaweb2/milestone/45?closed=1&page=2).

**Closed by nilmerg** 2018-05-02 07:31 UTC
Labels: bug, monitoring
