### ISSUE TITLE
Wrong sorting in access control

### ISSUE THREAD

**Issue by Nathaniel-Donahue** [Icinga/icingaweb2#5187] opened 2024-02-12 07:16 UTC
Hi there,

under Access Control > Roles, there's an option to sort by name, and when you press that button, it actually sorts something, but not correctly.

I expect it to sort something like this:
Apples
Bannans
Cherrys

This behavior seems to occur in Icinga Web 2 version 2.12.1

Regards,

**Comment by tbauriedel** [comment] 2024-02-12 07:30
ref/NC/807683

**Comment by nilmerg** [comment] 2024-02-12 11:23
Duplicate of #4789

**Closed by nilmerg** 2024-02-12 11:23 UTC

**Comment by nilmerg** [comment] 2024-11-05 08:19
Will be fixed with v2.12.2.
