### ISSUE TITLE
Feature Request: Make dependencies visible in icingaweb

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2#4188] opened 2020-06-23 07:02 UTC
dependencies are only visible via `icinga2 object list --type dependency. for users without knowledge on the commandline or users without access to the commandline  is it not easy to debug why a dependency hits or does not work or even is unexpected.

## Describe the solution you'd like
Maybe show them in the services/hosts with a link to information what this dependecies does
or a list like for the downtimes

**Comment by nilmerg** [comment] 2020-06-23 07:19
Hi,

there's already an issue for this. (#2378) Please add a comment there if you're interested.

**Comment by nilmerg** [comment] 2020-06-23 07:19
Duplicate of #2378

**Closed by nilmerg** 2020-06-23 07:19 UTC
