### ISSUE TITLE
Downtimes set with 'All Services' don't propagate removal when removing the host downtime

### ISSUE THREAD

**Issue by willfurnell** [Icinga/icingaweb2#4295] opened 2020-12-15 13:48 UTC
## Describe the bug

When setting a host downtime, I can check 'All Services' to have the downtime to apply to all the hosts services. However, when removing the host downtime, the module doesn't remove the downtimes it set on the services.

## To Reproduce
1. Have `hostdowntime_all_services=1` set in the monitoring module configuration
2. Create a new fixed downtime for a host
3. Do some work on the host that takes less time than the fixed downtime period
4. Click 'x' next to the host downtime to remove it
5. Services are still in downtime until the end of the period

## Expected behavior
If I check 'All Services' when making a downtime, I expect the downtime to be removed from them when I remove this downtime from the host.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 
Icinga Web 2 Version
    2.8.2
Git commit
    8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version
    7.3.11
Git commit date
    2020-08-17

* Web browser used: Firefox 83
* Icinga 2 version used (`icinga2 --version`): 2.12.2-1
* Server operating system and version: CentOS 7

**Comment by nilmerg** [comment] 2021-01-11 15:20
Duplicate of #3194

**Closed by nilmerg** 2021-01-11 15:20 UTC
