### ISSUE TITLE
Cookie Pi3 after logout

### ISSUE THREAD

**Issue by Crossovo** [Icinga/icingaweb2#3058] opened 2017-11-03 09:08 UTC
Hi,

I become in each browser (firefox, sfari, opera) a cookie error:

_Fatal error: Uncaught ErrorException: setcookie() expects parameter 3 to be integer, float given in /usr/share/php/Icinga/Web/Response.php:317 Stack trace: #0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'setcookie() exp...', '/usr/share/php/...', 317, Array) #1 /usr/share/php/Icinga/Web/Response.php(317): setcookie('icingaweb2-anno...', '{"acknowledged"...', 2147483648, '/icingaweb2/', NULL, false, true) #2 /usr/share/php/Icinga/Web/Response.php(329): Icinga\Web\Response->sendCookies() #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Response/Abstract.php(762): Icinga\Web\Response->sendHeaders() #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(975): Zend_Controller_Response_Abstract->sendResponse() #5 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #6 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch() #7 /usr/share/icingaweb in /usr/share/php/Icinga/Web/Response.php on line 317_

If I delete the cookies, than I can enter my login data and after that, I get the same error.

**Comment by lippserd** [comment] 2017-11-06 09:19
Hi,

Thanks for the report. This seems to be a bug with your announcements. Could you please share `/etc/icingaweb2/announcements.ini`?  You may back up and remove this file to get your Web 2 instance running.

Best regards,
Eric

**Comment by Crossovo** [comment] 2017-11-06 16:08
Hi Eric,

the file .../announcements.ini is empty. After I have removed the file, the system is still running now. 
Can I share other log files to verify how the error was created?

Regards Daniel

**Comment by lippserd** [comment] 2018-01-16 08:05
@Crossovo We tried to reproduce this issue but unfortunately without success. Log files won't help in this matter. I close this issue but if you face it again, please open a new issue.

**Closed by lippserd** 2018-01-16 08:05 UTC
