### ISSUE TITLE
`icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.`

### ISSUE THREAD

**Issue by astafev** [Icinga/icingaweb2#2940] opened 2017-09-04 16:08 UTC
For every command sent from UI I get an error:
`icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.`

I saw similar issues but didn't find any working solutions

## Expected Behavior
 on clicking "check now" or on executing any other action that supposed to be made by backend no errors should appear.

## Current Behavior
an error with the following stack trace:
```
#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(70): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleHostCheckCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1152): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(63): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostController.php(61): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostController->showAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```

## Your Environment

* Icinga Web 2 version and modules (System - About):
Version 2.4.1
Git commit d74124bd12f53d13b5a6ea5408e9783cc5190d1e
Git commit date 2017-01-18
  *  modules:
    director (btw, failed to setup it properly...)
    doc
    monitoring
    setup
* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.26.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
* Operating System and version (above).
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog gelf graphite influxdb livestatus opentsdb perfdata statusdata
Enabled features: api checker command ido-mysql mainlog notification syslog
* Config validation (`icinga2 daemon -C`):
```
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: ip-172-16-123-9
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'pagerduty-service' (in /etc/icinga2/conf.d/pagerduty-icinga2.conf: 60:1-60:49) for type 'Notification' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 1 SyslogLogger.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 2 UserGroups.
information/ConfigItem: Instantiated 20 Notifications.
information/ConfigItem: Instantiated 4 NotificationCommands.
information/ConfigItem: Instantiated 210 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 3 Hosts.
information/ConfigItem: Instantiated 3 Users.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 15 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

* Icingaweb and Icinga2 are installed on one host.
* `cat /etc/icinga2/features-enabled/command.conf`:
```
library "compat"

object ExternalCommandListener "command" { }
```
* `ll -a /var/run/icinga2/cmd/`
```
drwxr-s---. 2 icinga icingacmd 60 Sep  4 15:12 .
drwxr-xr-x. 3 icinga icingacmd 80 Sep  4 15:45 ..
prw-rw----. 1 icinga icingacmd  0 Sep  4 15:12 icinga2.cmd
```
* idea from #885: `su -s /bin/bash www-data -c 'test -w /var/run/icinga2/cmd/icinga2.cmd' || echo Permission\ denied` doesn't print the message

Please let me know if I can provide more info. Thanks.

**Comment by dnsmichi** [comment] 2017-09-04 16:32
SELinux?

**Comment by astafev** [comment] 2017-09-05 05:57
@dnsmichi turning it off following instructions from https://www.centos.org/docs/5/html/5.1/Deployment_Guide/sec-sel-enable-disable.html didn't help

**Comment by dnsmichi** [comment] 2017-09-05 06:51
And Icinga 2 is running and accepting commands too?

**Comment by dgoetz** [comment] 2017-09-05 09:11
User www-data looks like Debian/Ubuntu, so I do not think it is caused by SELinux, so lets start with DAC.
Is www-data in the group icingacmd? So provide output of `id www-data`.

**Comment by astafev** [comment] 2017-09-05 09:31
@dnsmichi Icinga2 is running fine, how to check that it's accepting commands?

@dgoetz yeah, you're right, sorry, this string is copied from the other issue, for my case it should be `apache` user.
```
[centos@ip-172-16-123-9 ~]$ id apache
uid=48(apache) gid=48(apache) groups=48(apache),993(icinga),992(icingacmd),991(icingaweb2)

```

**Comment by lippserd** [comment] 2017-09-20 13:03
Hi,

Did you restart your web server after you've added apache to the icingacmd group? I'm sure that this is a configuration issue so I close this one. If you're still having problems, please head over to our [community support channels](https://www.icinga.com/about/get-involved/).

Best regards,
Eric

**Closed by lippserd** 2017-09-20 13:03 UTC
Labels: no-issue, question
