### ISSUE TITLE
Menu items vanish shortly after page load (git master, icinga.js application state)

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#3752] opened 2019-04-17 09:39 UTC
## Describe the bug

Menu is there for a second, then it vanishes and only the search input is there. Latest Chrome.

![Screen Shot 2019-04-17 at 11 29 51](https://user-images.githubusercontent.com/382049/56277283-5a0bd880-6104-11e9-9aa6-8b268386b89c.png)

Same problem with Safari.

![Screen Shot 2019-04-17 at 11 37 14](https://user-images.githubusercontent.com/382049/56277863-6b091980-6105-11e9-8e13-95864caed1f9.png)

And Firefox.

![Screen Shot 2019-04-17 at 11 37 46](https://user-images.githubusercontent.com/382049/56277763-401ec580-6105-11e9-9bce-7c2e61b1f629.png)

## To Reproduce

1. Setup git master / snapshot packages (e.g. inside the Vagrant boxes in icinga-vagrant)
2. Modules: BP, Director, Reporting, Map, Elasticsearch
3. Login and open the dashboard
4. Open the dev console
5. Press refresh, the console logs this when the menu disappears

![Screen Shot 2019-04-17 at 11 33 36](https://user-images.githubusercontent.com/382049/56277479-b66ef800-6104-11e9-8a72-fba6a942ce14.png)

## Expected behavior

Menu stays there.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.2 14b6e4056231e12b4826432dfd7d5c60796e08b2
* Web browser used: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* PHP version used (`php --version`): PHP 7.1 SCL
* Server operating system and version: CentOS 7.6

**Comment by dnsmichi** [comment] 2019-04-17 09:41
Ah. I've disabled modules one by one. Once I disable Director 1.6.2 (stable), this starts to work again.

**Comment by dnsmichi** [comment] 2019-04-17 09:48
I suspect the changes from #3504 likely influence that. Changing to Director git master, https://github.com/Icinga/icingaweb2-module-director/commit/d3fa347ec2aa509d2d926ff86629cb118cbaaf63 doesn't change the behaviour, it remains kaputt.

@Thomas-Gelf anything which is different in menu item registering in Director than other modules?

**Comment by Thomas-Gelf** [comment] 2019-04-17 09:57
@dnsmichi: the pull request you linked touches `NavigationItemRenderer`, Director uses `setRenderer` in `configuration.php` to provide a `ConfigHealthItemRenderer` (Director, extends `BadgeNavigationItemRenderer`) and a `SummaryNavigationItemRenderer` (Icinga Web 2). You can try to disable one/both calls to `setRenderer` to verify whether this fixes the problem. In case it does please try how the change in the linked pull request could lead to the shown problem.

**Comment by nilmerg** [comment] 2019-04-17 10:52
Isn't this a dupe of https://github.com/Icinga/icingaweb2-module-director/issues/1837 ?

**Comment by dnsmichi** [comment] 2019-04-17 11:00
No, this is about the missing menu items. The linked issue is about the broken config form. I don't know if they relate to each other, I haven't seen TZ specific errors with the menu problem.

I'm currently testing something else, will come back to the suggested modifications later.

**Comment by nilmerg** [comment] 2019-04-17 11:01
Well, the error shown in menu on the screenshots is the same. :thinking:

**Comment by dnsmichi** [comment] 2019-04-17 11:09
Yep, because at this stage I wanted to just disable the Director, and clicked around in the Configuration form, triggering the exception there. You need to ignore the menu in the Director issue, I just was at the same software versions.

**Comment by dnsmichi** [comment] 2019-04-17 11:22
@Thomas-Gelf Confirmed, that renderer causes the problems.

![Screen Shot 2019-04-17 at 13 21 58](https://user-images.githubusercontent.com/382049/56284106-d5c15180-6113-11e9-976d-c7c21eddac89.png)

**Comment by Thomas-Gelf** [comment] 2019-04-17 12:01
@dnsmichi: as @nilmerg pointed out, the error shown on your screenshots reflects the linked issue. Icinga Web 2 is responsible for catching Errors in custom Item Renderers. In such case, the menu MUST fall back to the default renderer. This didn't happen because we ran into a fatal / parsing error. It would be nice if Icinga Web 2 would somehow handle those, but that's not a big issue as it shouldn't happen very often. Still, you might want to open a related issue.

If you can reproduce this error with the fix pushed by @nilmerg please show a new screenshot / error message. In such case we need to figure out what change in Icinga Web 2 triggered this. `ConfigHealthItemRenderer` extends `BadgeNavigationItemRenderer` in a very simple way.

**Comment by dnsmichi** [comment] 2019-04-17 12:17
Hm, hard to understand even with some knowledge about MVC and Icinga Web 2. The configuration controller is called, that error isn't seen anywhere (logs likely) that triggers a hard error, which then resets the application state of the menu. I don't think it will happen on userland though, more for developers who likely know already. I don't need that issue :)

Anyhow, it works now with the applied patch from @nilmerg so I'm fine. Actually I was just testing the reporting module deployed with Puppet ^_^

![Screen Shot 2019-04-17 at 14 17 08](https://user-images.githubusercontent.com/382049/56286994-8121d480-611b-11e9-963b-148231a902e7.png)

**Closed** 2019-04-17 12:18 UTC
Labels: bug
