### ISSUE TITLE
Collapsible Sidebar Issues

### ISSUE THREAD

**Issue by flourish86** [Icinga/icingaweb2#3187] opened 2017-12-05 10:05 UTC
This is a collection of some smaller issues i discovered regarding the collapsible sidebar implementation.

1) When the sidebar is collapsed, the navigation items scroll out of the visible area, when the search input is focussed. This could be reproduced in Safari. Expanding and collapsing again corrects this temporarily until the search input will be focussed again.

![bildschirmfoto 2017-12-04 um 17 57 18](https://user-images.githubusercontent.com/6977434/33565256-f0316706-d91c-11e7-91b4-0187382edc4b.png)

2) Active first-level nav item should be better distinguishable from non active ones (When first level index is selected).

![artboard 2](https://user-images.githubusercontent.com/6977434/40616530-bcb6de76-628b-11e8-9aa9-603f8916e809.png)

3) The toggle-sidebar "lug" could be spaced wider and taller to better align with the nav icons, especially in collapsed state. It should also get a little offset to bottom to align with the status bar, when available.

![artboard 3](https://user-images.githubusercontent.com/6977434/33600420-7a9cb378-d9a9-11e7-8ee4-976ec484a6f0.png)

4) The second level fly out menu appears after a slight delay after hovering. While the delay seems necessary for addressing the "scrollbar issue" for hiding the fly out, it should appear immediately when hovering.

5) In the original draft the flyout menu featured a caret on the left pointing to the according first level menu item. This doesn't harm usability too much, but should improve visual clarity, especially when another level-2 item is active.

![artboard 4](https://user-images.githubusercontent.com/6977434/33601222-e4522706-d9ab-11e7-8e0e-4ff5ac0f2a41.png)

## Your Environment
Icinga Web 2 2.5.0, screenshot taken in Safari 10.11.1 on macOS

**Comment by ratchetnclank** [comment] 2017-12-05 15:12
To add custom menu items which don't have an icon, just a name the text gets cut awkwardly when collapsed.

Perhaps just make it default to an icon of the first letter? Or some other generic default icon?

**Comment by lippserd** [comment] 2018-01-16 11:59
An icon of the first letter sounds like a good idea to me.

**Comment by flourish86** [comment] 2018-02-13 09:27
I also noticed, that the active level-2 item should not alter appearance when hovered, as there is no action behind the item.

Currently it opacity is reduced.

![screen shot 2018-02-13 at 10 18 39](https://user-images.githubusercontent.com/6977434/36142345-1564ca00-10a8-11e8-895d-e3c1c4c7078b.png)

**Comment by flourish86** [comment] 2018-05-28 13:29
edited item 2

**Comment by theFeu** [comment] 2018-05-29 12:59
Those should be fixed now:

> 2. The toggle-sidebar "lug" could be spaced wider and taller to better align with the nav icons, especially in collapsed state. It should also get a little offset to bottom to align with the status bar, when available.

It looka a bit wonky in the IE, but for the modern browsers (chrome, firefox, safari, android mobile, ...) it looks as intended.

> 4. The second level fly out menu appears after a slight delay after hovering. While the delay seems necessary for addressing the "scrollbar issue" for hiding the fly out, it should appear immediately when hovering.

Reduced the delay from 600 to 300 ms, so it feels a bit smoother

> I also noticed, that the active level-2 item should not alter appearance when hovered, as there is no action behind the item.
Currently it opacity is reduced.

This is now fixed.

**Comment by theFeu** [comment] 2018-05-29 13:09
Point 1 is only an issue in Safari, where ```overflow: hidden``` moves the menu bar 2em to the left, instead of hiding the overflow.
The menu bar is 2em wider than needs to be because of an issue with the scrollbar (width: 2em) in IE / Edge that needs to be hidden (with mentioned ```overflow: hidden```).

**Comment by lippserd** [comment] 2018-07-17 13:44
Not all issues @flourish86 mentioned have been fixed, so I'll remove the target version and we'll fix this with a version after the 2.6.0 release.

**Closed** 2019-03-21 08:09 UTC
Labels: bug, low-priority, ui
