### ISSUE TITLE
Open Redirect in Icinga Web Application Login Page

### ISSUE THREAD

**Issue by zacsmits** [Icinga/icingaweb2#4948] opened 2022-11-21 22:32 UTC
## Describe the bug
Arbitrary values can be passed into the 'redirect' parameter on the login page, redirecting the user to a chosen page which is not located in the Icinga web application.

## To Reproduce
 

1. POC URL: `https://<ip>/icingaweb2/authentication/login?redirect=http://google.com`

## Expected behavior
Icinga2 logs in and ignores the passed redirect parameters.

## Screenshots
Network profile below showing the initial load of login page with redirect url, ending with the load of google.com.au
![image](https://user-images.githubusercontent.com/94088163/203171102-de0646e7-f60c-4bc1-a8a4-cef6eeaa587a.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.2
* Web browser: Chrome, Firefox
* Icinga 2 version (icinga2 --version): 2.13.6
* Icinga DB version (icingadb --version): 1.0.0
* PHP version used (php --version): 7.4.3
* Server operating system and version: Ubuntu 20.04

## Additional context
N/A

**Comment by nilmerg** [comment] 2022-11-22 08:00
Duplicate of #4945

**Closed by nilmerg** 2022-11-22 08:00 UTC
