### ISSUE TITLE
show alerts in the browser

### ISSUE THREAD

**Issue by hboetes** [Icinga/icingaweb2#2996] opened 2017-10-06 12:16 UTC
I have a browser add on installed so I can see if icinga has a problem.
![selection_009](https://user-images.githubusercontent.com/2285225/31277220-313163ec-aaa0-11e7-88df-e77a480aaf21.png)

But wouldn't it be nice if the icinga tab itself could show notifications? I know I get allerts for new emails from gmail, so it is possible.

**Comment by lippserd** [comment] 2017-10-06 12:30
Hi,

Thanks for the report. I close this as duplicate of #2857.

Best regards,
Eric

**Closed by lippserd** 2017-10-06 12:30 UTC
