### ISSUE TITLE
Delete acknowledgment not working

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [Icinga/icingaweb2#4736] opened 2022-03-29 09:59 UTC
## Describe the bug
Since 2.10.0 the button "delete acknowledgment" isnt working anymore (no effect).

## To Reproduce
Click on "delete acknowledgment"  button.

## Expected behavior
Acknowledgment should be removed.

## Screenshots
![image](https://user-images.githubusercontent.com/53210931/160585609-668093ec-e047-4596-a2ea-1201dc986bb4.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):  2.10.0 (f1dc03fd8553fe58ef85ca6fb607fe2922c3e078)
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): r2.13.2-1
* PHP version used (`php --version`): 7.4.3
* Server operating system and version: Ubuntu 20.04.4

**Comment by nilmerg** [comment] 2022-03-29 10:11
Hi,

thanks for reporting, but this is a known issue.

**Comment by nilmerg** [comment] 2022-03-29 10:11
Duplicate of #4711

**Closed by nilmerg** 2022-03-29 10:11 UTC
