### ISSUE TITLE
Responsive missing Dashboards

### ISSUE THREAD

**Issue by schneif2** [Icinga/icingaweb2#4215] opened 2020-07-31 12:04 UTC
## Describe the bug
When you are using mobile phone in portrait mode, there are only the first three dashboards in top navigation visible. All other are hidden. Also in landscape mode there are a few more visible but not all.

## To Reproduce
Create serval Dashboards, Login to icingaweb2 via mobile phone or using developer tools in browser to reduce screen size, you can only see first dashboards, but not all. 
Main page {icingaweb2url}/dashboard

## Expected behavior
Something like sliding between dashboards like menu or button to unfold all other dashboards in new menu or additional lines.

## Screenshots
Google Chrome (everything okay)
![image](https://user-images.githubusercontent.com/48552719/89033019-2aeb9b80-d336-11ea-9d1f-45469d507447.png)

Google Chrome Dev Tools Portrait Mode (width 360px, missing critical filtered, Backup, Firewall, Mail)
![image](https://user-images.githubusercontent.com/48552719/89033048-3b9c1180-d336-11ea-8e9c-4c4a4c2bc959.png)

Google Chrome Dev Tools Landscape Mode (width 640px, missing mail)
![image](https://user-images.githubusercontent.com/48552719/89033082-566e8600-d336-11ea-876f-449e36dcbcd2.png)

## Your Environment
Icinga Web 2 Version: 2.7.3

Git commit: 06cabfe8ba28cf545a42c92f25484383191a4e51

Git commit date: 2019-10-18

Browser: Google Chrome on Windows 10, Google Chrome on Android

**Comment by nilmerg** [comment] 2020-08-10 12:37
Hi, thanks for the report. Though we already handle this elsewhere: #3461

**Comment by nilmerg** [comment] 2020-08-10 12:37
Duplicate of #3461

**Closed by nilmerg** 2020-08-10 12:37 UTC
