### ISSUE TITLE
Incompatiblity with php8.2

### ISSUE THREAD

**Issue by daku69** [Icinga/icingaweb2#5054] opened 2023-07-06 08:23 UTC
## Describe the bug
At the minimum, the setup on the webinterface is not possible to finish.

To use icingacli create errors.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

# Start webconfigureation
Coms the error message on the webinterface:
Deprecated
: Creation of dynamic property Zend_Validate_NotEmpty::$zfBreakChainOnFailure is deprecated in
/usr/share/icingaweb2/library/vendor/Zend/Form/Element.php
on line
2176

# start "icingacli help":
Deprecated: Creation of dynamic property Icinga\Clicommands\WebCommand::$trace is deprecated in /usr/share/php/Icinga/Cli/Command.php on line 61

## Environment

# Server
* Icinga Web 2 version: 2.11.4
* PHP version: 8.2
* OS: Debian trixie

# Client
* Web browser used: Firefox 93.0/Chromium 114.0.5735.106
* Debian bookworm

**Comment by nilmerg** [comment] 2023-07-06 08:36
Duplicate of #4918

**Closed by nilmerg** 2023-07-06 08:36 UTC
