### ISSUE TITLE
Deleted user does not remove account from group

### ISSUE THREAD

**Issue by withanhdammit** [Icinga/icingaweb2#5165] opened 2023-12-14 21:26 UTC
## Describe the bug
One person left the company, his account was deleted from 'users'.  Further investigation showed he was still a member of 'Monitoring Users' group, however when an attempt to remove from the group is made, it errors and does not remove the user
"Zend_Form_Element::_filterValue(): Argument #2 ($key) must be passed by reference, value given"

## To Reproduce
Add user, add user account to group
Delete user, attempt to delete from group

## Expected behavior
User account should be deleted from groups when the account is deleted

## Screenshots
![image](https://github.com/Icinga/icingaweb2/assets/16404870/9ab016dc-c9de-434e-85a4-e09b80f1edad)
![image](https://github.com/Icinga/icingaweb2/assets/16404870/3d25ae9c-82c2-440d-8bdf-8da8a3222498)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
2.12.1

* Web browser used:
Chrome or Edge

* Icinga 2 version used (`icinga2 --version`):
r2.14.0-1

* PHP version used (`php --version`):
8.0

* Server operating system and version:
Debian 10

**Comment by nilmerg** [comment] 2023-12-18 08:06
> "Zend_Form_Element::_filterValue(): Argument https://github.com/Icinga/icingaweb2/pull/2 ($key) must be passed by reference, value given"

Please upgrade `icinga-php-thirdparty` to v0.12.1.

**Comment by nilmerg** [comment] 2023-12-18 08:10
Duplicate of #3978

**Closed by nilmerg** 2023-12-18 08:10 UTC
