### ISSUE TITLE
Display of Custom Variables / Properties

### ISSUE THREAD

**Issue by Figment93** [Icinga/icingaweb2#4704] opened 2022-03-17 12:18 UTC
Hi All, 

I have been able to setup custom Data Fields and categories that display grouped and with the Display Name in Director like so;

![image](https://user-images.githubusercontent.com/57763509/158806180-01dbe708-ce44-4e6d-8dd3-e3bc3a26abcc.png)

However when looking at the Host Overview the Data Field is displayed under "Custom Variables" like so;

![image](https://user-images.githubusercontent.com/57763509/158806861-5db7b142-4958-442b-b738-703a20ccc712.png)

Is it possible to have these Data Fields show their Display name and to list them under their respective Data Categories instead in the host overview?

**Comment by nilmerg** [comment] 2022-03-17 12:39
Yes, planned for the upcoming release of Icinga Web 2 and Icinga Director.

**Comment by nilmerg** [comment] 2022-03-17 12:41
Duplicate of #3479

**Closed by nilmerg** 2022-03-17 12:41 UTC

**Comment by Figment93** [comment] 2022-03-17 12:47
thank you @nilmerg !
