### ISSUE TITLE
Backend icinga is not running between CEST to CET timezone change

### ISSUE THREAD

**Issue by zangetsu05** [Icinga/icingaweb2#3606] opened 2018-10-28 01:24 UTC
During the time between 02:00:00 CEST until 2:59:59 CEST,  there was this error on
the web interface:
"Backend icinga is not running"
Everything was fine on the server and the message lasted till the 2:59:59 CEST, then
at 3 o'clock in the morning the timezone changed to CET, the time returned to 2 o'clock,
and no errors anymore.
System have the right timezone configuration, the same php, the same mysql.

I can't find a solution during the problem, at first I didn't think that the problem 
was related to the change of the time here in Italy, but in the end is something 
related to this.

The only way to reproduce this, I think, is with a virtual server with date and clock
near the time between CEST => CET, in 2018 it happen during the night between
27-28 October at 3 o'clock. 

* Icinga Web 2 version and modules (System - About): 2.6.1
* Version used (`icinga2 --version`): r2.10.1-1
* Operating System and version: CentOS 7
* Enabled features (`icinga2 feature list`): api checker command compatlog ido-mysql livestatus mainlog notification perfdata statusdata syslog
* Config validation (`icinga2 daemon -C`):
[2018-10-28 02:20:16 +0100] information/cli: Icinga application loader (version: r2.10.1-1)
[2018-10-28 02:20:16 +0100] information/cli: Loading configuration file(s).
[2018-10-28 02:20:16 +0100] information/ConfigItem: Committing config item(s).
[2018-10-28 02:20:16 +0100] information/ApiListener: My API identity: hqmonitormaster.fibering.com
[2018-10-28 02:20:18 +0100] warning/ApplyRule: Apply rule 'backup-downtime-fibering' (in /etc/icinga2/fibering.d/downtimes.conf: 5:1-5:61) for type 'ScheduledDowntime' does not match anywhere!
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 882 Services.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 LivestatusListener.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 SyslogLogger.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 657 Hosts.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 805 Dependencies.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 4 NotificationCommands.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1539 Notifications.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 23 HostGroups.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 23 Comments.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 3 Zones.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 StatusDataWriter.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 Endpoint.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 ApiUser.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 CompatLogger.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 7 Users.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 228 CheckCommands.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 4 UserGroups.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 6 ServiceGroups.
[2018-10-28 02:20:18 +0100] information/ConfigItem: Instantiated 4 TimePeriods.
[2018-10-28 02:20:18 +0100] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2018-10-28 02:20:18 +0100] information/cli: Finished validating the configuration file(s).

**Comment by lippserd** [comment] 2018-11-16 16:06
Hi,

Thanks for the report. I'll see what we can do here.

Best,
Eric

**Comment by nilmerg** [comment] 2019-04-10 11:30
This is a duplicate of #3525. Closed.

**Closed by nilmerg** 2019-04-10 11:30 UTC
Labels: bug
