### ISSUE TITLE
Icingaweb2 Fatal Error directly after installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by skip3rr** [Icinga/icingaweb2#4143] opened 2020-04-29 16:44 UTC
After Icinga2+Icingaweb2 installation and try to open /icingaweb2/setup, the fatal error appears:

Fatal error: Uncaught ErrorException: Uncaught ErrorException: include(): \Icinga\Web\ViewStream::stream_set_option is not implemented! in /usr/share/php/Icinga/Web/View.php:262 Stack trace: #0 /usr/share/php/Icinga/Web/View.php(262): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}() #1 /usr/share/php/Icinga/Web/View.php(262): include() #2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run() #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render() #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript() #5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render() #6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch() #7 /usr/share/icin in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259

My Environment
PHP 7.4.3 
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 20.04 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.4.0-28-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 9.2.1
  Build host: lcy01-amd64-022

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

**Comment by nilmerg** [comment] 2020-04-30 06:01
Hi, you'd need v2.8.0-rc1 for this to work.

Duplicate of #4009.

**Closed by nilmerg** 2020-04-30 06:01 UTC

**Comment by skip3rr** [comment] 2020-04-30 07:13
But i have 2.11.2 it is not compatible ?

**Comment by lippserd** [comment] 2020-04-30 07:18
Hi @skip3rr,

If you have Icinga DB in mind here and don't want to use it right now, that is no problem. Icinga 2.11.2 + Web 2.8.0 RC1 work just fine together. Please also read this https://github.com/Icinga/icinga2/issues/7957

All the best,
Eric

**Comment by skip3rr** [comment] 2020-04-30 07:58
Hi,
It is working fine. 
Thank you for help :)

**Comment by lippserd** [comment] 2020-04-30 08:05
You're welcome.
