### ISSUE TITLE
Feature Request - Create a Dashboard without beeing rendered in the controls tabs section

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2#4811] opened 2022-06-10 04:34 UTC
## Is your feature request related to a problem? Please describe.

I created many Dashboards and some of the are accessible via MenuSections.
Most of them are a combination of more views like in the "monitoring/configuration.php"
My Problem is, that the navigation bar gets a little bit overcrowded.

```
/*
 * Custom Dashboard
 */
$dashboard = $this->dashboard(N_('Dashboard1'), array('priority' => 50));
$dashboard->add(
    N_('Part1'),
    'monitoring/list/services?service_problem=1&limit=10&sort=service_severity',
    100
);
$dashboard->add(
    N_('Part2'),
    'monitoring/list/services?service_state=0&limit=10&sort=service_last_state_change&dir=desc',
    110
);
$dashboard->add(
    N_('Part3'),
    'monitoring/tactical',
    120
);
```

## Describe the solution you'd like
A Parameter for Dashboard Panes that hides the dashboard from the top navigation bar
`$dashboard = $this->dashboard(N_('Dashboard1'), array('priority' => 50,  hidden=>true);`

Or a way to reuse / partial render more than one dashlets

## Describe alternatives you've considered
Currently I hide the unwanted Dashboards via a module.js javascript and a blacklist

**Comment by nilmerg** [comment] 2022-06-10 06:53
If they're hidden, how can you access them?

Note that it's planned to [collapse too wide tabs into an expandable "..." menu](https://github.com/Icinga/icingaweb2/issues/3416).
There's also work underway to be able to group dashboards by so called *homes*. (https://github.com/Icinga/icingaweb2/issues/3809#issuecomment-1098039274)

**Comment by moreamazingnick** [comment] 2022-06-10 09:15
if they are hidden on the top, the url of the pane still works and they can be accessed via
`
$section = $this->menuSection(N_('Somehidden Menu'), array(
    'icon'      => 'attention-circled',
    'priority'  => 20
));

$section->add(N_('Some Link to hidden Dashboard'), array(
    'icon'        => 'service',
    'description' => $this->translate('List current X problems'),
    'url'       => 'dashboard?pane=Dashboard1',
    'priority'  => 60
));

`

**Comment by nilmerg** [comment] 2022-06-10 09:18
I see! Then those *homes* I've talked about are what you need.

**Comment by nilmerg** [comment] 2022-06-10 09:18
Duplicate of #3809

**Closed by nilmerg** 2022-06-10 09:18 UTC
