### ISSUE TITLE
wrong and all the same timestamp in history after upgrading to 2.11.0

### ISSUE THREAD

**Issue by boredbonobo** [Icinga/icingaweb2#4867] opened 2022-07-06 09:01 UTC
## Description
In history view of any service everywhere is the same timestamp of 1:33am. As if i click on the event the correct time is displayed under state timestamp. So i consider the timestamp in the database is correct, but a wrong timestamp is displayed unter host->service->history in the list. 

## To Reproduce

1. click on a host
2. click on services in top navigation
3. click on a service
4. click on history

## Expected behavior
Before the last upgrade the history showed the correct timestamps and it was ordered desc separated by the date like

september, 15, 2022
check_http - down since 10:45:22

## Screenshots
![image](https://user-images.githubusercontent.com/93453647/177511862-3cee6a72-7a9b-4776-92ec-5da958e807b0.png)

## Environment
OS: Debian 11
Virtual Machine
Icinga-Bullseye-Repository
MariaDB: v10.5.15-0+deb11u1
PHP: 7.3.33-4+0~20220627.98+debian11~1.gbp40b3e4
Icinga2 v2.13.4-1.bullseye
icingaweb2 v2.11.0-1.bullseye
Database Upgrades done for icinga2 and icingaweb2
Webbrowser: Chrome 103.0.5060.114
![image](https://user-images.githubusercontent.com/93453647/177512870-ff895e04-35e9-409d-aca2-94f0559e4ff8.png)

**Comment by ToonSpinISAAC** [comment] 2022-07-06 09:34
This looks like it was already reported in #4853, and the fix is slated to be added in 2.11.1.

**Comment by boredbonobo** [comment] 2022-07-06 11:35
thx for the hint

**Comment by nilmerg** [comment] 2022-07-07 09:17
v2.11.1 has just been released with the fix for this included.

**Comment by nilmerg** [comment] 2022-07-07 09:17
Duplicate of #4853

**Closed by nilmerg** 2022-07-07 09:17 UTC
