### ISSUE TITLE
Allow wildcards in the roles configuration

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2#2915] opened 2017-08-10 05:56 UTC
In Icinga Web 2.2.x I used to define a role with `users="*"`, this does not seem to work any more. Did the syntax change? Giving it a quick look I did not found anything related in our code. I could imagine something like:

```php
    // library/Icinga/Authentication/AdmissionLoader.php
    protected function match($username, $userGroups, ConfigObject $section)
    {
           //...
            if (in_array($username, $users)) {
                return true;
            }
+           if (in_array('*', $users)) {
+               return true;
+           }
```

@lippserd: do you have a hint for me?

**Comment by lippserd** [comment] 2017-08-10 06:28
Hi Tom,

I don't remember whether this was possible before :). Do you think it is a good idea to use `*` as a wildcard for match anything after the asterisk? We could match `john*` then for example.

Cheers,
Eric

**Comment by Thomas-Gelf** [comment] 2017-08-10 07:00
Sure, why not. And the same for groups. Only remaining question: what if someone has a user named `John Doe (***OLD ACCOUNT***)` - or similar? Use escape sequences in our users/groups properties, like `\*`?

**Comment by lippserd** [comment] 2017-11-16 10:59
We postpone the match stuff but add the "Apply a role to all users" feature with #3095

**Comment by mtdeguzis** [comment] 2019-03-26 15:01
I can confirm wildcard "*" works for me. Thought there is no way I see to check what role a user actually has without confirming via functionality tests.

**Comment by lippserd** [comment] 2019-05-06 11:21
The "match all" functionality seems to be sufficient. I close this one.

**Closed by lippserd** 2019-05-06 11:21 UTC
Labels: enhancement
