### ISSUE TITLE
Business Processes - Services right container empty

### ISSUE THREAD

**Issue by k67078** [Icinga/icingaweb2#4604] opened 2021-11-15 11:03 UTC
## Describe the bug
In Business Processes, when clicking down to a service in a process node the right container usually shows the service information.
Now after the upgrade to 2.9.4 the right container is empty.

## To Reproduce
1. In Business Processes click on the menu.
2. Click  on process nodes all the way to services or hosts
3. Click on Host or Service Process Node. 
4. Usually Host or service monitoring information shows up in the right container. 

## Expected behavior
Right container should show host or service monitoring information.

## Screenshots
![image](https://user-images.githubusercontent.com/48209256/141771004-479182da-6c65-41ed-9430-11ccf445c80e.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
  * Icinga Web 2 Version: 2.9.4
  * Business Processes Version: 2.3.1
  * IPL Version: 0.7.0
* Web browser used: Chrome, MS Edge and Firefox
* Icinga 2 version used (`icinga2 --version`): 2.13.1-1
* PHP version used (`php --version`): 7.3.31-1
* Server operating system and version: Debian 10 (buster)

**Comment by k67078** [comment] 2021-11-15 12:56
After downgrading to icingaweb2 2.9.3, Business Processes is back to normal again..

**Comment by sukhwinder33445** [comment] 2021-11-15 13:09
Duplicate of #4598

**Closed by sukhwinder33445** 2021-11-15 13:09 UTC
