### ISSUE TITLE
Send action for Hostgroup/Servicegroup

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#3244] opened 2018-01-04 09:21 UTC
Hi,
A customer of mine asks for a feature to send an action to a hostgroup/servicegroup at once. They have rather large hostgroups so scrolling and selecting is rather cumbersome.
I could think of a small bar above the list of hosts in the detailview of the hostgroup. So it will still look like it does now but with small buttons/keywords for "plan downtime", "check now" and so on on top of the list.
Maybe it could be a good idea to send the actions in batches because I know some users really do have very big groups and as far as I remember Icinga 2 can not take an action based on membership but wants to have all host-/servicenames sent individually.
Cheers,
Thomas

**Comment by thammw** [comment] 2018-01-08 14:55
This feature is already available with usage of the API(e.g. filtering for host.group: https://server:5665/v1/objects/hosts?filter="yourhostgrouphere" in host.groups).

Iirc icingaweb2 has a problem with scheduling anything if there are more than x hosts involved(because the URL is way to long).

**Comment by widhalmt** [comment] 2018-01-09 08:44
Thanks for pointing that out.
We have some customers who can only use Icinga Web 2 for sending commands for various reasons. So I'm afraid this won't fix the issue.

**Comment by lippserd** [comment] 2018-01-15 08:46
Hi,

Thanks for the report. I close this as duplicate of #2344.

Best regards,
Eric

**Closed** 2018-01-15 08:46 UTC
Labels: duplicate
