### ISSUE TITLE
icingaweb2 not working with PHP 7.4

### ISSUE THREAD

**Issue by d3ns0n** [Icinga/icingaweb2#4140] opened 2020-04-24 19:48 UTC
I upgraded to Ubuntu 20.04 yesterday and noticed that icingaweb2 is not running any more. It seems that to be connected to the upgrade from php7.2 to php7.4. When I open the icingaweb2 login URL I see the following error:

`Fatal error: Uncaught ErrorException: Uncaught ErrorException: include(): \Icinga\Web\ViewStream::stream_set_option is not implemented! in /usr/share/php/Icinga/Web/View.php:262 Stack trace: #0 /usr/share/php/Icinga/Web/View.php(262): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}() #1 /usr/share/php/Icinga/Web/View.php(262): include() #2 /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run() #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render() #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript() #5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render() #6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch() #7 /usr/share/icin in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 259`

It seems to be a backward incompatible change in PHP 7.4: https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.stream-wrappers

**Comment by nilmerg** [comment] 2020-04-27 05:55
Duplicate of #4009

**Closed by nilmerg** 2020-04-27 05:55 UTC
