### ISSUE TITLE
A theme with different colors for SOFT and HARD states

### ISSUE THREAD

**Issue by gdubicki** [Icinga/icingaweb2#4160] opened 2020-05-21 16:05 UTC
## Is your feature request related to a problem? Please describe.
Most of the time I would like to ignore services that are in SOFT Critical state. But currently on a first glance they look the same as the ones in HARD Critical state because of the same color.

## Describe the solution you'd like
I would like to be able to create a color theme where a different color is used for SOFT and HARD Critical state and to create a new theme based on the default one that uses it. I would leave the current theme as default. 

## Describe alternatives you've considered
None.

## Additional context
Now:
<img width="100" alt="Screenshot 2020-05-21 at 18 00 04" src="https://user-images.githubusercontent.com/566632/82578631-eb157480-9b8c-11ea-8ec2-99e2fd388330.png">
My (bad) mockup of how a different colors could look like:
<img width="100" src="https://user-images.githubusercontent.com/566632/82578892-4f383880-9b8d-11ea-9d46-e745b841c0a4.png">

**Comment by ozzi-** [comment] 2020-05-22 14:05
+1 on this

**Comment by nilmerg** [comment] 2020-11-17 08:52
Hi,

meanwhile, Icinga DB is really a thing and we went a very different way with it regarding state color/representation. (The dots now represent the remaining check attempts until it switches to a hard state)

![Screenshot from 2020-11-17 09-47-19](https://user-images.githubusercontent.com/16668527/99367216-f6d2c100-28b9-11eb-9d65-11494193b166.png)

Also, to not confuse users being used to the light state color representing a handled state, I don't think showing soft states differently is a good idea.

I close this then in favor of [Icinga DB Web](https://github.com/Icinga/icingadb-web).

**Closed by nilmerg** 2020-11-17 08:52 UTC

**Comment by geotekberlin** [comment] 2022-07-18 07:45
I would also strongly welcome a clear visual differentiation between soft and hard errors so that our technicians can concentrate on hard errors. Soft errors are important and should be shown, **but in our environment only hard states need immediate manual action**. In Icingaweb2 the soft error states were at least ordered on top of the list, so it was cumbersome but at least possible to find the list position where the hard states were beginning and ignore everything above.

I hoped so much that this would be solved in IcingaDB Web but it has gotten worse. Now we can't even differentiate between soft and hard states at all: 
 
![IcingaDB Isues](https://user-images.githubusercontent.com/15341250/179463244-5fa18489-68ea-4a4f-8280-522a456ca9fb.png)

This morning II showed a preview of the new IcingaDB Web GUI to our technicians, and they did not want to use IcingaDB Web at all because this would mean more work for them.

**Comment by nilmerg** [comment] 2022-07-19 08:24
@geotekberlin What you're showing are all hard states. A soft state would have the dots under the visual (as I showed above).

Though, isn't that only a matter of sorting the list as required by your technicians? There Icinga DB Web has already an advantage, as it allows to sort for more than one column, it's just not adjustable in the UI yet...

Try this and check back with them if it suits them: `/icingaweb2/icingadb/services?service.state.is_problem=y&sort=service.state.state_type,service.state.severity%20desc`

**Comment by geotekberlin** [comment] 2022-07-19 14:03
@nilmerg, your query shows only hard states and hides all soft states completely. But this is not what I want. Compare it with riding a car: You wouldn't would want a long list of identical sized error LEDs where loss of oil pressure has the same visual representation as the eco warning for an open window.  Not even if there were some tiny dots below the eco warning light saying that you may ignore this warning for a while. (Sorry for the sarcasm ;-) 

That means I always want soft and hard errors to be shown, as it is now, but they must be 

1. easily and immediately visually distinguishable
2. separately grouped, unless explicitly ordered by name or something else.

One solution that comes to my mind would be to use pie icons similar to these:

![Icinga Soft Error Icons](https://user-images.githubusercontent.com/15341250/179764378-7682b13f-7294-4eaa-ba03-d523ba4767b5.jpg)

The icons would symbolize from 1 of 8 to 8 of 8 failed checks from left to right. Their meaning would be intuitively comprehensible and with the increasing number of failed checks they would become more and more conspicuous, which is a nice, added benefit.

I think this visual representation could be easily applied to all other states (unknown, warning,...) and would not interfere with the concept of showing confirmed alerts in a washed out color, which is also very intuitive. The pie dots can also be rendered in the browser via HTML5 so that it won't add backend load.

Wouldn't that be a big improvement?

**Comment by geotekberlin** [comment] 2022-07-19 15:46
You are right, with the original query all soft states are grouped in a separate section at the end, but that disrupts the logic of ordering events into alerts, warnings and undefined, because no one would expect to find more alerts at the end of the list after all hard alerts, warnings and undefined have been shown. 

However, your last query

`/icingaweb2/icingadb/services?service.state.is_problem=y&sort=service.state.severity%20desc,service.state.state_type`

is indeed useful. It keeps the alert states grouped together, but puts the soft states at the end of each state group. 

**If this becomes the default ordering in the host and service problem menus or could be at least centrally enforced for all users, we could live well with that solution.**

As a side note, I would still suggest discussing the graphical state representation with a web usability professional. I am sure he/she will agree that the representation of hard (= real, affirmed) states and soft (= possibly temporary, not yet affirmed) states would much be more intuitive and visually distinguishable with pie slices than with identical icons for both kinds and added dots for soft errors. But let's finish this pie vs dot discussion here. It was only a recommendation from my point of view as an Icinga user, and  I think you have gotten my point, haven't you?
