### ISSUE TITLE
Extend button for 2nd container

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2#5103] opened 2023-09-03 10:33 UTC
## Describe the bug
We have several dashboards and these are just be spread across the width of the screen.
But if you then request a detail/list in a dashboard, open a 2nd container for the detail/list, a whole part of the menu is no longer visible including the close button.

## To Reproduce
Create multiple dashboards that fill your screen and then open a detail in one of your dashboards.
The close button is gone.

## Expected behavior
That the close button always remains on the screen

## Suggestion
Is it not possible to place an extra button in the 2nd container , next to the close button, that turns the detail screen as the main screen.

Something like this

![focus](https://github.com/Icinga/icingaweb2/assets/29303758/a9329fe6-a60a-4e5e-9ab7-f96ac8c3a8fb)

regards,
Geert

**Comment by nilmerg** [comment] 2023-09-04 07:00
Duplicate of #3461

**Closed by nilmerg** 2023-09-04 07:00 UTC
