### ISSUE TITLE
Sorting roles by their name doesn't work

### ISSUE THREAD

**Issue by MisterMountain** [Icinga/icingaweb2#4999] opened 2023-02-10 11:32 UTC
## Describe the bug
If you try to sort your Icingaweb2 roles in ascending or descending order by their name does not work. It does not change anything, although the sorting does get rendered to the URL (like /icingaweb2/role/list?sort=name&dir=desc)

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Go to /icingaweb2/role/list
2. Create at least two roles with different names (like Foo, Bar and Test)
3. Try to sort them in ascending or descending order
4. See that nothing changes

## Expected behavior
The roles get sorted in ascending or descending order by their name

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): Icinga Web 2 2.11.4
* Web browser used: Firefox 109.0.1
* Icinga 2 version used (`icinga2 --version`): r2.13.6-1
* PHP version used (`php --version`): PHP 8.1.2
* Server operating system and version: Ubuntu Jammy

**Comment by MisterMountain** [comment] 2023-02-10 11:32
ref/NC/776412

**Comment by nilmerg** [comment] 2023-02-10 11:44
Sorry, but this won't be fixed as mentioned here: #4789

**Comment by nilmerg** [comment] 2023-02-10 11:45
Duplicate of #4789

**Closed by nilmerg** 2023-02-10 11:45 UTC

**Comment by nilmerg** [comment] 2024-11-05 08:19
Will be fixed with v2.12.2.
