### ISSUE TITLE
Icinga Web 2.8.3/2.9.0 display Icinga 2 custom variable arrays and dictionaries incorrectly

### ISSUE THREAD

**Issue by peteeckel** [Icinga/icingaweb2#4488] opened 2021-07-27 13:46 UTC
## Description
If the Icinga 2 custom variables for an object contain an array or a dictionary, the display in the Icinga Web 2 2.9.0 and 2.8.3 "Custom Variables" section is no longer correct. Instead of displaying the array name and the array elements in an indented list, the elements of the array are displayed as individual values to variables consisting of integers. Instead of displaying a dictionary, all of its elements are simply listed as scalars.

### Icinga 2 Variables
```
  * vars
    % = modified in '/var/lib/icinga2/api/zones/global/_etc/templates-host.conf', lines 6:5-6:14
    % = modified in '/var/lib/icinga2/api/zones/dmz/_etc/host-medusa11.conf', lines 18:5-28:5
    * certificate_lifetime
      * le-mx1
        * cert_lifetime_certfile = "/etc/pki/letsencrypt/certs/mx1.example.com"
        * cert_lifetime_filetype = "PEM"
    * command_endpoint = "medusa11.dmz.example.com"
      % = modified in '/var/lib/icinga2/api/zones/dmz/_etc/host-medusa11.conf', lines 30:5-30:61
    * groups = [ "virtual_guest", "centos8", "dmz", "icinga_agent", "bareos_client", "bareos_servers", "postfix_servers", "mailman_servers", "mta_servers", "mail_servers", "hbr", "icinga_monitoring" ]
      % = modified in '/var/lib/icinga2/api/zones/dmz/_etc/host-medusa11.conf', lines 6:5-6:191
    * os
      % = modified in '/var/lib/icinga2/api/zones/dmz/_etc/host-medusa11.conf', lines 8:5-14:5
      * architecture = "x86_64"
      * distribution = "AlmaLinux"
      * major_version = "8"
      * type = "Linux"
      * version = "8.3"
    * zone = "medusa11.dmz.example.com"
      % = modified in '/var/lib/icinga2/api/zones/dmz/_etc/host-medusa11.conf', lines 16:5-16:49
```

### Display in Icinga Web 2.9.0/2.8.3
![Screenshot 2021-07-27 at 15 15 06](https://user-images.githubusercontent.com/6815386/127162975-11494834-5521-4020-9238-62086262655e.jpg)

### Display in Icinga Web 2.8.2
![Screenshot 2021-07-27 at 15 27 55](https://user-images.githubusercontent.com/6815386/127162381-0f96744e-7034-4268-ad9d-f7ea9822f16e.jpg)

## Expected behavior
The "Custom Variables" section preserves the structure of complex variables.

## Environment
* Icinga Web 2 version and modules (2.9.0):
Icinga Web 2 Version 2.9.0
Git commit 3b0a0a78df9389c46d3a74611a8eaec2f2b3cc77
PHP Version 7.3.20
Git commit date 2021-07-12

* Icinga Web 2 version and modules (2.8.3):
Icinga Web 2 Version 2.8.3
Git commit 479f990d5981354c05c362700117fe086cd048a9
PHP Version 7.3.20
Git commit date 2021-07-12

* Web browser used:
Safari 14.1.2
Firefox 90.0.2

* Icinga 2 version used (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.5-2)
Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
System information:
  Platform: AlmaLinux
  Platform version: 8.4 (Electric Cheetah)
  Kernel: Linux
  Kernel version: 4.18.0-305.el8.x86_64
  Architecture: x86_64
Build information:
  Compiler: GNU 8.4.1
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020
Application information:
General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2
Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var
Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* PHP version used (`php --version`):
PHP 7.3.20 (cli) (built: Jul  7 2020 07:53:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies

* Server operating system and version:
AlmaLinux release 8.4 (Electric Cheetah)

**Comment by nilmerg** [comment] 2021-07-27 13:54
Hi, thanks for your report, but this is a known issue: #4439

**Comment by nilmerg** [comment] 2021-07-27 13:54
Duplicate of #4439

**Closed by nilmerg** 2021-07-27 13:54 UTC
