### ISSUE TITLE
[dev.icinga.com #13529] Ability to see check command invocation (with parameters) from the web interface, for debugging issues.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2642] opened 2016-12-12 12:22 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13529

**Created by kowalskimn on 2016-12-12 12:22:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-12 12:22:12 +00:00 (in Redmine)_

---

I often face problems when service check does not run the way i expect it to, and one of the most tricky things in icinga2 for me is to figure out what arguments are actually passed to it to understand the problem.

It would be nice to be able to see the entire command invocation, for debugging purposes. Since it may contain passwords and other critical data, such feature might be restricted to specific users. Or it might be visible to everyone, but less privileged users will see the passwords hashed out.

Thruk interface contains similar functionality, but it doesn't distinguish (afaik) who will see the command invocation. Entire command with all arguments can be extracted with icinga-studio, but it's not a very optimal solution.

**Comment by dnsmichi** [comment] 2017-08-24 15:00
Duplicate of #1344

**Closed by dnsmichi** 2017-08-24 15:00 UTC
Labels: enhancement
