### ISSUE TITLE
"unhandled services" count host host view differences with different query filters

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icingaweb2#3921] opened 2019-08-15 11:34 UTC
## Describe the bug
in icingaweb2, when I go to "Tactical Overview" -> "Hosts" and filter for a specific host group, I have found one Host who has no unhandled services shown (the red text in braces).
But when I add the specific host name to the filter (or filter only for this specific host) I get the (correct) number of unhandled services for this host.
Strange: As far, as I can see, this behaviour exists only for this host (can't go through all hosts and check it manually)

Summarizing: You can't rely for the info in braces about unhandled services in "Tactical Overview" -> "Hosts"

## To Reproduce
Don't know how to reproduce. Currently I found only this host with this behaviour

## Expected behavior
the information about unhandled services in host view should always the same correct one 

## Screenshots
![Screenshot from 2019-08-15 11-43-18_filter_with_hg](https://user-images.githubusercontent.com/740897/63091885-2630aa80-bf60-11e9-8df8-c8c1faa3c0e4.png)
![Screenshot from 2019-08-15 11-44-09_filter_with_hg_and_host](https://user-images.githubusercontent.com/740897/63091887-2630aa80-bf60-11e9-825a-c2919bf1064c.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.6.3
* Web browser used: Firefox 68
* Icinga 2 version used (`icinga2 --version`): 2.8.2
* PHP version used (`php --version`): 7.1
* Server operating system and version: rhel 7 (64 Bit)

**Comment by lippserd** [comment] 2019-08-15 11:43
Hi,

Thanks for the report. Which RDBMS are you using for the Icinga 2 database, i.e. MySQL or PostgreSQL?

Best,
Eric

**Comment by tlo8640** [comment] 2019-08-15 11:53
Hi,
Thank you for the fast reply
sorry, I totally forgot the DB:

> mysql -u***** -p -h ***** icinga2ido_db
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

> Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 6726858
Server version: 10.1.26-MariaDB MariaDB Server

> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

It's a 5 Node Galera Cluster runnig on RHEL 7 (64 Bit)

**Comment by tlo8640** [comment] 2019-08-28 14:49
Hello,
any news on that?
can I provide additional info? What could help?
DB Queries?
Thank you and best regards
Thomas

**Comment by nilmerg** [comment] 2019-09-09 10:56
Is this still an issue with 2.7.0 or 2.7.1? We've had fix included there that did involve wildcard matching.

Though, I can't reproduce this either with v2.6.3 or v2.7.1. :thinking:

**Comment by tlo8640** [comment] 2019-09-09 11:18
Hello,

thanks for answer.
We are still on 2.6.3
Unfortunately I can't reproduce it, too
I found this on only one host of 3000. I can't look manually through all of them looking for differences. I really don't know why exactly this host shows this strange behavior.
Other servers (as far as i can see) show the correct information

**Comment by nilmerg** [comment] 2019-09-09 12:59
Sorry, but then I'll close this now. If you observe this again (with v2.7.0+) feel free to re-open the issue.

**Closed** 2022-02-28 12:05 UTC
Labels: bug, area/monitoring
