### ISSUE TITLE
Dashboards in HA-Environment

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2#3580] opened 2018-09-24 18:46 UTC
## Expected Behavior
In a HA environment icingaweb2 dashboards are available to the user no matter on which node they are saved.

## Current Behavior
icingaweb2 saves the dahboard configuration in files so you have to setup some kind of file sync on all nodes in an HA environment.

## Possible Solution
Save dashboard config in database

**Comment by dgoetz** [comment] 2018-09-26 07:13
This is a duplicate of #1704

**Comment by lippserd** [comment] 2018-11-14 08:59
Hi,

Thanks for the report. I close this as duplicate.

Best,
Eric

**Closed by lippserd** 2018-11-14 08:59 UTC
Labels: duplicate
