### ISSUE TITLE
Long host- and servicenames can overlap the right UI tab

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2#3944] opened 2019-09-05 09:42 UTC
## Describe the bug
Long hostnames overlap the right part of the Icingaweb2 UI. This is a bit irritating.

## To Reproduce
You need a long host- or servicename and an error in the right tab:

![image](https://user-images.githubusercontent.com/34264690/64330673-aaaba180-cfd1-11e9-9a4e-04dcc17a9562.png)

I found this during the reproduction of another issue.

## Expected behavior
Host- and servicenames should not cloak the right UI tab.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

Icinga Web 2 Version
    2.7.1
Git Commit
    b0bf9c4b0637f6113adb788e78c2bcf619225dd8
PHP Version
    7.1.8
Git Commit Datum
    2019-08-14
Copyright
    © 2013-2019 Das Icinga Projekt 

* Web browser used:
Firefox developer edition 69.0b16
Chrome Version 76.0.3809.132 (Offizieller Build) (64-Bit)
IE 11 

* Icinga 2 version used (`icinga2 --version`):

icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)

* PHP version used (`php --version`):

PHP 5.4.16 (cli) (built: Jun 19 2018 13:09:01)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

* Server operating system and version:

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.6 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-957.21.3.el7.x86_64
  Architecture: x86_64

**Comment by nilmerg** [comment] 2019-09-09 13:03
That's for you @flourish86, since you like to fix such edge cases :grin:

**Comment by nilmerg** [comment] 2019-09-16 11:53
@K0nne We weren't able to reproduce this the way you've shown it. But rest assured we'll make sure this won't survive monitoring's next evolution :wink:

**Comment by K0nne** [comment] 2019-09-16 15:07
Thanks for your effort! I have a talent for edgy bugs ^^

**Comment by nilmerg** [comment] 2020-02-27 09:20
Hi, I was now able to reproduce this. However, only with the latest release, on the master it seems to have been already fixed by #3904.

**Closed by nilmerg** 2020-02-27 09:20 UTC
Labels: area/monitoring, area/ui, bug
