### ISSUE TITLE
Navigation: Argument 1 passed to ipl\Web\Widget\Icon::_construct() must be of type string, null given

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2#5266] opened 2024-09-24 07:19 UTC
## Describe the bug
We use shared navigation. One user shares a navigation structure with all other users. Since our switch to "icingadb-web" this behaviour occured. With the "monitoring" module, this did not happen.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Click on an navigation item with sub-entries to expand
2. the error occures reproduceable

## Expected behavior
If you click on a navigation item with sub entries, it expands and on the right side of the ui it souldn't expect a parameter for the right side. 

## Screenshots
![image](https://github.com/user-attachments/assets/e5505224-5dfc-4bab-b266-6f97ea7fa9ff)

![image](https://github.com/user-attachments/assets/a6af8c5b-dc2c-4192-8e2f-4d8b3914f8ea)

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.1.2
* Icinga Web 2 version (System - About): 2.12.1
* Web browser: edge
* Icinga 2 version (`icinga2 --version`): 2.13.9
* Icinga DB version (`icingadb --version`): 1.2.0
* PHP version used (`php --version`):7.2.24
* Server operating system and version: rhel8

**Comment by nilmerg** [comment] 2024-09-24 08:18
Duplicate of #5177

**Closed by nilmerg** 2024-09-24 08:18 UTC
