### ISSUE TITLE
Navigation Panel spanning multiline on firefox ESR

### ISSUE THREAD

**Issue by ninjakitteh69** [Icinga/icingaweb2#3991] opened 2019-11-04 15:06 UTC
## Describe the bug
When one of the navigational menu's are closed and there is an issue, the red / yellow badge appears showing the number. when this badge appears, it jumps to the next line instead of just displaying next to the text. if you hover over, it continually opens and closes the menu as it spans from 1 line to 2

## To Reproduce
Install the latest version of icinga and icingaweb2.
once there is an alert, the badge should display and it will span to a new line. 

## Expected behavior
The number should display next to the text instead of displaying underneath

## Screenshots
How its reacting:
![Screenshot-2019-11-4 My Account Icinga Web](https://user-images.githubusercontent.com/21240594/68130814-b3164f00-ff24-11e9-8931-a250080a5b0c.png)

how it should display:
![Screenshot-2019-11-4 Problems Icinga Web](https://user-images.githubusercontent.com/21240594/68130950-ea84fb80-ff24-11e9-896f-57f2cbbd7b63.png)

## Your Environment
* Icinga Web 2 version and modules (System - About) :2.7.3 (been doing this since icinga v2.5.x)
* Web browser used: Firefox 60.9.0esr (chrome seems to be fine)
* Icinga 2 version used (`icinga2 --version`): 2.11.2-1
* PHP version used (`php --version`): 7.1.30
* Server operating system and version: Centos 7.7.1908

**Comment by akqopensystems** [comment] 2019-11-05 14:30
+1

**Comment by nilmerg** [comment] 2019-11-06 08:25
Duplicate of #3791

As mentioned there, this should be fixed with Firefox 68.0esr which has been released on 9th July.

**Closed by nilmerg** 2019-11-06 08:25 UTC
