### ISSUE TITLE
Setup-Wizard: Error due to /icingaweb2/setup at Requirements page

### ISSUE THREAD

**Issue by tachtler** [Icinga/icingaweb2#4837] opened 2022-06-28 06:26 UTC
## Describe the bug
After basic installation of icinga2 and icingaweb2 an error occurs on /icingaweb2/setup on page Requirements

## To Reproduce

1. Install icinga2 and icingaweb2
2. Start installed apache with configure php-fpm and configuraton for php-fpm and icingaweb2
3. Start with URL: /icingaweb2/setup
4. Step Requirement --> an ERROR occurs.

## Expected behavior
/icingaweb2/setup is working as expected

## Screenshots
```
Uncaught TypeError: Icinga\Module\Setup\RequirementSet::key(): Return value must be of type int, null returned in /usr/share/webapps/icingaweb2/modules/setup/library/Setup/RequirementSet.php:314
Stack trace:
#0 /usr/share/webapps/icingaweb2/modules/setup/library/Setup/RequirementSet.php(293): Icinga\Module\Setup\RequirementSet->key()
#1 [internal function]: Icinga\Module\Setup\RequirementSet->valid()
#2 /usr/share/webapps/icingaweb2/modules/setup/library/Setup/RequirementsRenderer.php(36): RecursiveIteratorIterator->next()
#3 /usr/share/webapps/icingaweb2/modules/setup/library/Setup/RequirementsRenderer.php(62): Icinga\Module\Setup\RequirementsRenderer->render()
#4 /usr/share/webapps/icingaweb2/modules/setup/library/Setup/RequirementSet.php(333): Icinga\Module\Setup\RequirementsRenderer->__toString()
#5 /usr/share/webapps/icingaweb2/modules/setup/application/views/scripts/form/setup-requirements.phtml(11): Icinga\Module\Setup\RequirementSet->__toString()
#6 /usr/share/webapps/icingaweb2/library/Icinga/Web/View.php(235): include('...')
#7 /usr/share/webapps/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#8 /usr/share/webapps/icingaweb2/library/vendor/Zend/View/Helper/Partial.php(106): Zend_View_Abstract->render()
#9 /usr/share/webapps/icingaweb2/library/vendor/Zend/View/Abstract.php(345): Zend_View_Helper_Partial->partial()
#10 /usr/share/webapps/icingaweb2/library/Icinga/Web/View.php(251): Zend_View_Abstract->__call()
#11 /usr/share/webapps/icingaweb2/library/vendor/Zend/Form/Decorator/ViewScript.php(173): Icinga\Web\View->__call()
#12 /usr/share/webapps/icingaweb2/library/vendor/Zend/Form.php(2974): Zend_Form_Decorator_ViewScript->render()
#13 /usr/share/webapps/icingaweb2/library/Icinga/Web/Form.php(1559): Zend_Form->render()
#14 /usr/share/webapps/icingaweb2/modules/setup/application/views/scripts/index/parts/wizard.phtml(1): Icinga\Web\Form->render()
#15 /usr/share/webapps/icingaweb2/library/Icinga/Web/View.php(235): include('...')
#16 /usr/share/webapps/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#17 /usr/share/webapps/icingaweb2/modules/setup/application/views/scripts/index/index.phtml(140): Zend_View_Abstract->render()
#18 /usr/share/webapps/icingaweb2/library/Icinga/Web/View.php(235): include('...')
#19 /usr/share/webapps/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run()
#20 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render()
#21 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript()
#22 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#23 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#24 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#25 /usr/share/webapps/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#26 /usr/share/webapps/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#27 /usr/share/webapps/icingaweb2/library/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#28 /usr/share/webapps/icingaweb2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#29 /usr/share/webapps/icingaweb2/public/index.php(4): require_once('...')
#30 {main}
thrown
```
```
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

## Your Environment

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version | 2.10.1 (974729a6421c17fdb8bb1931623107cf6a90fc7e)

# icinga2 feature list
Disabled features: command compatlog debuglog elasticsearch gelf graphite icingadb ido-pgsql influxdb influxdb2 livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification

# icingacli module list
MODULE         VERSION   STATE     DESCRIPTION
monitoring     2.10.1    enabled   Icinga monitoring module
setup          2.10.1    enabled   Setup module
```
* Web browser used:
```
Firefox on Archlinux -> 101.0.1 (64-bit)
```
* Icinga 2 version used (`icinga2 --version`):
```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.3-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Arch Linux
  Platform version: Unknown
  Kernel: Linux
  Kernel version: 5.15.50-1-lts
  Architecture: x86_64

Build information:
  Compiler: GNU 12.1.0
  Build host: vml250
  OpenSSL version: OpenSSL 1.1.1p  21 Jun 2022

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* PHP version used (`php --version`):
```
# php -version
PHP 8.1.7 (cli) (built: Jun 10 2022 13:49:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
```
* Server operating system and version:
```
# cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

## Additional context
```
# php -m
[PHP Modules]
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
imagick
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
SimpleXML
sockets
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

**Comment by nilmerg** [comment] 2022-06-28 06:42
Hi,

that's because up until version 2.11 Icinga Web is not compatible with PHP 8.1.

**Comment by nilmerg** [comment] 2022-06-28 06:43
Duplicate of #4609

**Closed by nilmerg** 2022-06-28 06:43 UTC
