### ISSUE TITLE
Allow to set downtime for all hosts in a hostgroup

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2#3264] opened 2018-01-16 08:21 UTC
## Expected Behavior
I would like to set downtime for all hosts in a hostgroup with fewer clicks like having an action near the hostgroup.

## Current Behavior
If I click on the hostgroup I get a filtered list of hosts, have to multiselect and send them all in a downtime from the tab with the selection. This can also fail when a hostgroup is very big.

## Possible Solution
Add an action next to the hostgroups or something similar matching the UI design.

## Context
Setting downtimes based on hostgroups was quite easier with classic UI and Icinga Web 1.

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.4.2
* Version used (`icinga2 --version`): 2.7.1
* Operating System and version: RHEL 7

**Comment by lippserd** [comment] 2018-01-16 11:40
Hi Dirk,

Thanks for the report. I close this as duplicate of #2344.

Cheers,
Eric

**Closed** 2018-01-16 11:40 UTC
Labels: duplicate
