### ISSUE TITLE
Unable to add a service view to dashboard

### ISSUE THREAD

**Issue by tobiasneumayer** [Icinga/icingaweb2#3198] opened 2017-12-07 08:37 UTC
After upgrading from Icinga Web 2 2.4.2 to 2.5.0 on Ubuntu 16.04.3 LTS my self created dashboard was gone and now I´m unable to add a host / service again. 

To add a new host / service to the dashboard I went to the searchbar, typed in the host / service name and clicked on it. In the host / service site I clicked on the arrow and selected the option "Add to Dashboard". After typing in the name and choosing the dashboard "Current Incidents" I clicked on "Add to Dashboard".

If I now go back to the Homepage / Dashboard (http://<servername>/icingaweb2/dashboard), there are no entries. 

If I now click on the arrow on the top bar and go to "Settings", there are only the default links for e.g. Server Problems, Host Problems, ... 

* Icinga Web 2 version and modules (System - About): Icinga Web 2 - 2.5.0
* Version used (`icinga2 --version`): r2.8.0-1
* Operating System and version: Ubuntu 16.04.3 LTS
* Config validation (`icinga2 daemon -C`): 
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
warning/ApplyRule: Apply rule 'backup-downtime' (in /etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 Endpoint.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ConfigItem: Instantiated 963 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 219 CheckCommands.
information/ConfigItem: Instantiated 25 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 247 Hosts.
information/ConfigItem: Instantiated 1 Comment.
information/ConfigItem: Instantiated 3 UserGroups.
information/ConfigItem: Instantiated 3 Users.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 736 Services.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 CompatLogger.
information/ConfigItem: Instantiated 1 StatusDataWriter.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by dnsmichi** [comment] 2017-12-07 08:43
Hi,

it is hard to imagine with pure text. Can you please add some screenshots of what you're doing, step by step. Also add the exact URLs for those views.

Kind regards,
Michael

**Comment by tobiasneumayer** [comment] 2017-12-07 10:59
Hi,

thanks for your fast reply. Problem is now fixed after logout and login again.
Do you think it is ok, or should it work out of the box without re-login?

Best regards,
Tobias

**Comment by lippserd** [comment] 2017-12-07 11:42
The re-login fixed it. We changed the variable used for the username and your "old" session did not reflect this. We should add this to our upgrade docs though.

**Comment by lippserd** [comment] 2018-01-17 11:23
Duplicate of #3277.

**Closed by lippserd** 2018-01-17 11:23 UTC
Labels: documentation, framework
