### ISSUE TITLE
Not acknowledged services multiplied

### ISSUE THREAD

**Issue by MaBauMeBad** [Icinga/icingaweb2#3051] opened 2017-10-24 18:47 UTC
## Expected Behavior
![image](https://user-images.githubusercontent.com/32883466/31961638-94ba976c-b8fb-11e7-99b2-5f0d0a2f401b.png)

 Shown the unacknowledged services

## Current Behavior
The number of unacknowledged services got multiplied with the Number of Hostgroups the host is within. 

So if the Host is a member in two Hostgroups, 2 unacknowledged services are shown

![image](https://user-images.githubusercontent.com/32883466/31961531-4396a830-b8fb-11e7-9a3e-0a3a03843833.png)

This issue only appears if you filter for Hostgroups in the Icingaweb2 Permisson Roles.

The filter we use for monitoring/filter/objects: hostgroup_name=HG-ITO_*|hostgroup_name=HG-eSmaC*|hostgroup_name=HG-Icinga2

The Hostgroups all are standalone and not included in each other.
Alle Hostgroups are simple like

> 
object HostGroup "HG-linux-servers" {
  display_name = "Linux Servers"

  assign where host.vars.os == "Linux"
}

> 

## Steps to Reproduce (for bugs)
Open the Host view in Icingaweb2, and look for an hhost with more than one Hostgroup and unacknowledged Services.

## Context
The wrong count of the unacknowledged Services may confuse some people und lead to unnecessary discussion.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.4.2  (This issue also appears with Icingaweb2.4.1)
* Version used (`icinga2 --version`):
`icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.3 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-97-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: a9edf83df4f7`

* Operating System and version: Ubuntu 16.04 LTS

**Comment by MaBauMeBad** [comment] 2017-10-25 15:09
https://monitoring-portal.org/index.php?thread/42216-not-acknowledged-services-multiplied/&postID=257859#post257859

**Comment by MaBauMeBad** [comment] 2017-11-08 11:58
Could anyone confirmed this issue ?

**Comment by lippserd** [comment] 2017-11-10 09:19
I close this as duplicate of #2822

**Closed by lippserd** 2017-11-10 09:19 UTC
Labels: bug
