### ISSUE TITLE
SQL Error in Overview -> ContactGroups

### ISSUE THREAD

**Issue by barsukNastya** [Icinga/icingaweb2#2907] opened 2017-08-02 07:39 UTC
```
Stacktrace
SQLSTATE[HY000]: General error: 1111 Invalid use of group function, query was: SELECT cgo.name1 AS contactgroup_name, cg.alias COLLATE latin1_general_ci AS contactgroup_alias, COUNT(cgm.contactgroup_member_id) AS contact_count FROM icinga_contactgroups AS cg
INNER JOIN icinga_objects AS cgo ON cgo.object_id = cg.contactgroup_object_id AND cgo.is_active = 1 AND cgo.objecttype_id = 11
LEFT JOIN icinga_contactgroup_members AS cgm ON cgm.contactgroup_id = cg.contactgroup_id
LEFT JOIN icinga_objects AS co ON co.object_id = cgm.contact_object_id AND co.is_active = 1 AND co.objecttype_id = 10 WHERE (COUNT(cgm.contactgroup_member_id) = 'dhdh') GROUP BY cg.contactgroup_id,
cgo.object_id ORDER BY cgo.name1 ASC LIMIT 25
```

My Environment:
icingaweb2 version 2.4.1

URL:
.../monitoring/list/contactgroups?contact_count=qw&modifyFilter=1

**Comment by lippserd** [comment] 2017-08-02 08:16
Hi,

Please share the query string of the URL.

Best regards,
Eric

**Comment by barsukNastya** [comment] 2017-08-02 09:36
.../monitoring/list/contactgroups?contact_count=qw&modifyFilter=1

**Comment by barsukNastya** [comment] 2017-08-03 04:34
URL:
.../monitoring/list/contactgroups?contact_count=qw&modifyFilter=1

**Comment by lippserd** [comment] 2017-09-21 08:16
Hi,

This is a duplicate of #1354. Though `qw` is not a valid count, the real issue is that Web 2 does not use `having` for the filter.

Best regards,
Eric

**Closed by lippserd** 2017-09-21 08:16 UTC
Labels: needs-feedback

**Comment by Thomas-Gelf** [comment] 2017-09-21 08:30
@lippserd, just a hint, not directly related to above issue: the filter itself shouldn't care, the decision whether to use a `having` or a `where` clause should be up to the (data) view. It might also be able to figure out whether `where` would fit and fall back to a safer (but eventually slower) `having` in case grouping is involved.

**Comment by lippserd** [comment] 2017-09-21 08:35
Hi Tom,

Yeah, sure. Only the view/query knows which column is an aggregation column.

Cheers,
Eric
