### ISSUE TITLE
Error after creating announcement

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingaweb2#3734] opened 2019-04-05 09:10 UTC
i've created an announcement insigt icingaweb, after the APPLY ive only got an error....

## Current Behavior
This message is on the TOP Left from the Icingaweb2:
Couldn't parse the INI file `/etc/icingaweb2/announcements.ini'

And this is the error on: System\Announcement:

Couldn't parse the INI file `/etc/icingaweb2/announcements.ini'

#0 /usr/share/php/Icinga/Application/Config.php(326): Icinga\File\Ini\IniParser::parseIniFile(String)
#1 /usr/share/php/Icinga/Application/Config.php(397): Icinga\Application\Config::fromIni(String)
#2 /usr/share/php/Icinga/Repository/IniRepository.php(391): Icinga\Application\Config::app(String)
#3 /usr/share/php/Icinga/Repository/IniRepository.php(91): Icinga\Repository\IniRepository->createConfig(Array, String)
#4 /usr/share/php/Icinga/Repository/RepositoryQuery.php(112): Icinga\Repository\IniRepository->getDataSource(String)
#5 /usr/share/php/Icinga/Repository/Repository.php(704): Icinga\Repository\RepositoryQuery->from(String, Array)
#6 /usr/share/icingaweb2/application/controllers/AnnouncementsController.php(32): Icinga\Repository\Repository->select(Array)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AnnouncementsController->indexAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}
syntax error, unexpected '"' in Unknown on line 4
#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/File/Ini/IniParser.php(265): parse_ini_string(String, Boolean, Integer)
#2 /usr/share/php/Icinga/Application/Config.php(326): Icinga\File\Ini\IniParser::parseIniFile(String)
#3 /usr/share/php/Icinga/Application/Config.php(397): Icinga\Application\Config::fromIni(String)
#4 /usr/share/php/Icinga/Repository/IniRepository.php(391): Icinga\Application\Config::app(String)
#5 /usr/share/php/Icinga/Repository/IniRepository.php(91): Icinga\Repository\IniRepository->createConfig(Array, String)
#6 /usr/share/php/Icinga/Repository/RepositoryQuery.php(112): Icinga\Repository\IniRepository->getDataSource(String)
#7 /usr/share/php/Icinga/Repository/Repository.php(704): Icinga\Repository\RepositoryQuery->from(String, Array)
#8 /usr/share/icingaweb2/application/controllers/AnnouncementsController.php(32): Icinga\Repository\Repository->select(Array)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AnnouncementsController->indexAction()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.6.2
* Version used (`icinga2 --version`):  r2.10.4-1
* Operating System and version: Ubuntu 16.04.6 LTS
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql mainlog notification perfdata
* Config validation (`icinga2 daemon -C`):
[2019-04-05 11:03:24 +0200] information/cli: Icinga application loader (version: r2.10.4-1)
[2019-04-05 11:03:24 +0200] information/cli: Loading configuration file(s).
[2019-04-05 11:03:24 +0200] information/ConfigItem: Committing config item(s).
[2019-04-05 11:03:24 +0200] information/ApiListener: My API identity: smon03.intranet.stg
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 2303 Services.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 400 Hosts.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 4 NotificationCommands.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 2090 Notifications.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 15 HostGroups.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 Downtime.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 GraphiteWriter.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 PerfdataWriter.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 6 Comments.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 116 Zones.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 ExternalCommandListener.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 114 Endpoints.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 2 ApiUsers.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 4 Users.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 230 CheckCommands.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 2 UserGroups.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 5 ServiceGroups.
[2019-04-05 11:03:25 +0200] information/ConfigItem: Instantiated 5 TimePeriods.
[2019-04-05 11:03:26 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-04-05 11:03:26 +0200] information/cli: Finished validating the configuration file(s).

* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by nilmerg** [comment] 2019-04-05 09:14
Hi,

yeah sorry, that's a bug introduced with v2.6.2. Already reported with #3705 and fixed in the master.

Though, it only fixes the cause. Not the issue itself. You'll need to fix the file `/etc/icingaweb2/announcements.ini` by yourself. Newlines need either be removed or replaced with a literal `\n`.

e.g.
```ini
[abcdefgh]
author = "icingaadmin"
message = "te\nst"
...
```

**Closed by nilmerg** 2019-04-05 09:14 UTC

**Comment by ChristianMoritz** [comment] 2019-04-05 10:04
thx 4 the hint... so it works....
