### ISSUE TITLE
openssl_cipher_iv_length(): Unknown cipher algorithm

### ISSUE THREAD

**Issue by francesco-giordano** [Icinga/icingaweb2#4497] opened 2021-07-29 08:44 UTC
## Describe the bug
Using the RememberMe function we get this error
![immagine](https://user-images.githubusercontent.com/8560837/127460526-5330ba87-b6d1-44f0-b10f-a8c7c9448fac.png)

We have identified that come from this file /usr/share/php/Icinga/Crypt/AesCrypt.php where the upper case of the cipher cause this function to fail

`$len = openssl_cipher_iv_length($this->method);`

to solve the error, in the constructor we have changed the method to lowercase

NOT WORKING

```php
    /** @var string The cipher method */
    private $method = 'AES-128-GCM';

    const GCM_SUPPORT_VERSION = '7.1';

    public function __construct($random_bytes_len = 128)
    {
        if (version_compare(PHP_VERSION, self::GCM_SUPPORT_VERSION, '<')) {
            $this->method = 'AES-128-CBC';
        }

        $this->key = random_bytes($random_bytes_len);
    }
```
WORKING
```php
    /** @var string The cipher method */
    private $method = 'aes-128-gcm';

    const GCM_SUPPORT_VERSION = '7.1';

    public function __construct($random_bytes_len = 128)
    {
        if (version_compare(PHP_VERSION, self::GCM_SUPPORT_VERSION, '<')) {
            $this->method = 'AES-128-CBC';
        }

        $this->key = random_bytes($random_bytes_len);
    }
```
## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.2
* Web browser used: Chrome
* Icinga 2 version used (`icinga2 --version`): 2.12.5
* PHP version used (`php --version`): 7.3.20 and 7.1
* Server operating system and version: Red Hat Enterprise Linux Server release 7.8 (Maipo)

**Comment by gbin2265** [comment] 2021-07-30 15:56
Hello,

I made the adjustments and everything is fine now.

I'm going to wait for the new version/rpm, test again, before I upgrade my production environment.

thank you for the support !

regards,
Geert

**Comment by nilmerg** [comment] 2021-08-02 08:18
Duplicate of #4493

**Closed by nilmerg** 2021-08-02 08:18 UTC
