### ISSUE TITLE
Services are no longer sorted in Icingaweb 2.7

### ISSUE THREAD

**Issue by winem** [Icinga/icingaweb2#3901] opened 2019-08-05 13:57 UTC
## Describe the bug
The services were sorted alphabetically with the previous releases.

## To Reproduce
Choose any host and click on `Services`. The services appear in random order.

## Expected behavior
The services should appear in alphabetical order. 

## Screenshots
![Selection_402](https://user-images.githubusercontent.com/1457899/62469887-7e65f080-b799-11e9-8245-be2d41081a47.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.7.0
* Web browser used: Firefox, Chrome, reproducable with any browser
* Icinga 2 version used (`icinga2 --version`): 2.10.5-1
* PHP version used (`php --version`): 7.3.5
* Server operating system and version: Ubuntu 18.04 

## Additional context
This might be related to https://github.com/Icinga/icingaweb2/issues/3891

**Comment by bunghi** [comment] 2019-08-06 06:46
+1

I have the same problem with the History tab, entries are not sorted in any order.. :(

**Comment by dgoetz** [comment] 2019-08-06 07:13
I can confirm this and add dashboards are also now sorted differently.

**Comment by PitWenkin** [comment] 2019-08-06 07:44
> I can confirm this and add dashboards are also now sorted differently.

#3889 dashboard sorting was apparently never supposed to be possible …

**Comment by winem** [comment] 2019-08-06 13:33
> I have the same problem with the History tab, entries are not sorted in any order.. :(

Oh true, saw that for the history entries as well which is actually the bigger issue for us. Thanks for pointing it out.

**Comment by lippserd** [comment] 2019-08-07 11:02
Hi,

Thanks for the report. I close this as duplicate of #3891. Will be fixed asap.

Best,
Eric

**Closed by lippserd** 2019-08-07 11:02 UTC
Labels: duplicate
