### ISSUE TITLE
v 2.10 Upper "check now" button stopped working

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2#4739] opened 2022-03-30 11:56 UTC
Hi all,
we recognized, that since the update to 2.10, the upper "check now" stopped working in service overviews. On click, whether the notification "Scheduling check" appears, nor is the check excuted or the check intervall is reseted. A click on the lower "check now" next to the "last check" timestamp is still working.
Occurs in Chrome and Firefox.

Cheers,
Marcus

**Comment by nilmerg** [comment] 2022-03-30 12:23
Hi,

thanks for the report, but this is a known issue.

**Comment by nilmerg** [comment] 2022-03-30 12:23
Duplicate of #4711

**Closed by nilmerg** 2022-03-30 12:23 UTC
