### ISSUE TITLE
After upgrade to 2.6.2 acknowledgement and setting downtime not possible

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingaweb2#3651] opened 2018-12-12 16:20 UTC
## Expected Behavior

Acknowledgement and setting Downtimes should work like in Version 2.6.1

## Current Behavior

We upgraded to Icingaweb2 2.6.2 today. And after upgrading it is not possible to set acknowledgements and downtimes. We get following Errors:

Acknowledgement:
![image](https://user-images.githubusercontent.com/38723488/49882526-1a20a600-fe31-11e8-951a-230394ee0c33.png)

Downtime:
![image](https://user-images.githubusercontent.com/38723488/49882544-2442a480-fe31-11e8-8e9a-94626d64b5b1.png)

And that's from the icingaweb2-log:
![image](https://user-images.githubusercontent.com/38723488/49882668-610e9b80-fe31-11e8-8005-fc28d6e2d9b5.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.2
* Version used (`icinga2 --version`): 2.10.2
* Operating System and version: CentOS 7.6
* Enabled features (`icinga2 feature list`):
Disabled features: compatlog debuglog elasticsearch gelf graphite livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command ido-mysql influxdb mainlog notification

if you Need more Information let us now. At the meantime I'll try to downgrade.

**Comment by martinrw** [comment] 2019-01-02 09:41
I'm having the same issue. If there is any troubleshooting info that I can provide I'll try my best to provide it

**Comment by dnsmichi** [comment] 2019-01-07 08:32
PHP version?

**Comment by stevie-sy** [comment] 2019-01-07 08:35
7.1.8-1.e17

**Comment by martinrw** [comment] 2019-01-07 08:55
I'm on rh-php71-1-1.el7.x86_64
After spending a while looking into the problem on my server with no luck I gave in and restarted the icinga2 service which actually resolved the issue (I imagine only temporarily though)

**Comment by dnsmichi** [comment] 2019-01-07 23:41
Which command transport is used here?

**Comment by stevie-sy** [comment] 2019-01-08 06:06
we are using the api

**Comment by martinrw** [comment] 2019-01-08 08:55
API as well for us

**Comment by lippserd** [comment] 2019-01-08 09:34
@stevie-sy According to the logs you've shared, the API URL looks a bit odd: `localhost:0`. Could you please share the contents of `/etc/icingaweb2/modules/monitoring/commandtransports.ini`. Please omit the `username` and `password` directives. @martinrw please share this file too.

**Comment by lippserd** [comment] 2019-01-08 09:39
We use the following code in order to build the API endpoint:

```php
        $defaults = array(
            'host'  => 'localhost',
            'path'  => '/'
        );

        $url = array_merge($defaults, parse_url($urlFromConfig));
```
If `$urlFromConfig` is `localhost:0` then `parse_url()` returns false.

**Comment by martinrw** [comment] 2019-01-08 09:40
`[icinga2]
transport = "api"
host = "172.16.0.138"
port = "5665"
username = "icingaweb2"
password = "password"`

and just in case there is some difference between mine and Stevie-sy's logs, here is an example of what I saw in the log when it happened:

`Jan  2 09:07:53 icinga-ha-master0 icingaweb2[1525]: Icinga\Module\Monitoring\Exception\CurlException in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Rest/RestRequest.php:291 with message: Operation timed out after 30000 milliseconds with 0 out of 0 bytes received
Jan  2 09:07:53 icinga-ha-master0 icingaweb2[1525]: Icinga\Module\Monitoring\Exception\CommandTransportException in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Command/Transport/CommandTransport.php:137 with message: icinga2: Operation timed out after 30000 milliseconds with 0 out of 0 bytes received.    #0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/ScheduleServiceDowntimeCommandForm.php(192): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceDowntimeCommand))    #1 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/ScheduleHostDowntimeCommandForm.php(108): Icinga\Module\Monitoring\Forms\Command\Object\ScheduleServiceDowntimeCommandForm->scheduleDowntime(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceDowntimeCommand), Object(Icinga\Web\Request))    #2 /usr/share/php/Icinga/Web/Form.php(1158): Icinga\Module\Monitoring\Forms\Command\Object\ScheduleHostDowntimeCommandForm->onSuccess()    #3 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostsController.php(76): Icinga\Web\Form->handleRequest()    #4 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostsController.php(201): Icinga\Module\Monitoring\Controllers\HostsController->handleCommandForm(Object(Icinga\Module\Monitoring\Forms\Command\Object\ScheduleHostDowntimeCommandForm))    #5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\HostsController->scheduleDowntimeAction()    #6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)    #7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))    #8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))    #9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()    #10 /usr/share/icingaweb2/public/index.php(4): require_once(String)    #11 {main}
`

**Comment by lippserd** [comment] 2019-01-08 09:50
@martinrw Which Icinga 2 version are you using? It seems that Icinga does not respond to the API request within 30 seconds. We are kind of aware of this problem and are in the process of fixing it. It would be great if you could help us here. I created a patch which adds a new timeout option to the `RestRequest` class which we are using in order to send commands to the Icinga API. With this option, Icinga Web stops the Request if we can't connect (TCP) to the Icinga API within 3 seconds. You may apply this patch with `patch -d /usr/share/icingaweb2 -p1 <RestRequest.php.patch.txt`. Please retry a command afterwards and provide feedback whether you get an exception after 3 seonds.
[RestRequest.php.patch.txt](https://github.com/Icinga/icingaweb2/files/2736155/RestRequest.php.patch.txt)

**Comment by martinrw** [comment] 2019-01-08 10:02
Hi @lippserd 
Our icinga2 version is: icinga2-2.10.2-1.el7.icinga.x86_64
Happy to try and help testing the patch...The problem is currently not occurring since I restarted the service So I'll run a quick test to make sure it doesn't break anything else and next time I see the issue will try again to see if it fixes it.
Do you know if there is a way to induce this behaviour?
Looks like my issue might be slightly different to Stevie-sy, is there a better place to discuss your restrequest patch?

**Comment by stevie-sy** [comment] 2019-01-08 10:12
@lippserd  here you are 
[icinga2]
transport = "api"
host = "localhost"
port = "5665"
username = "icingaweb2"
password = "xxxxxxxxx"

Is this new with the parsing function in 2.6.2? Because in previous version (<= 2.6.1) it works very well for us. 

On every deployment with the director the icinga.service is automaticly restarted.

**Comment by stevie-sy** [comment] 2019-04-10 18:17
a small update on this:

We installed a new test environment and here we had the same problem. It seems there is a problem with the plugin "Monitoring". 
As you can see it's the same configuration in the file "commandtransports.ini" like in our production system and it's correct. But if we take a look into the backend Information of the module you'll see, that in the textbox is written port 0 instead port 5665 like the config file. 

![image](https://user-images.githubusercontent.com/38723488/55902583-21cc3d80-5bcc-11e9-8c78-02504a6999dd.png)

Maybe the module reads the information in a wrong way from the config file. Because after editing the wrong port in the config menue everything is working like before.

**Comment by nilmerg** [comment] 2019-04-30 12:42
This seems to be the same as in #3733. PHP version 7.1.8 is also one of the affected versions. Since #3733 is part of 2.6.3 released last week and the initial issue seems solved I'll close this now.

**Closed by nilmerg** 2019-04-30 12:42 UTC
Labels: needs-feedback
