### ISSUE TITLE
Problem with "Check now" on the top bar of the service page.

### ISSUE THREAD

**Issue by tachtler** [Icinga/icingaweb2#4735] opened 2022-03-29 08:41 UTC
## Describe the bug
Problem with "Check now" on the top bar of the service page.

## To Reproduce

1. Click on Overview
2. Choose a Service
3. Click on Button "Check Now (Jetzt prüfen)" on the **top bar of the service page**
4. --> Nothing happens!

## Expected behavior
If you click the Button "Check Now (Jetzt prüfen)" **inside the service page**, it **still works!**

## Screenshots
![icingaweb2](https://user-images.githubusercontent.com/11161944/160570526-52d45af6-8f03-4273-9310-713910fc0753.png)

## Your Environment
* Icinga Web 2 version and modules (System - About): 2.10.0
* Web browser used: Mozilla Firefox 98.0.2
* Icinga 2 version used (`icinga2 --version`):
```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.13.2-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1160.59.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* PHP version used (`php --version`): 
```
# php --version
PHP 7.2.24 (cli) (built: Nov  4 2019 10:23:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
* Server operating system and version: 
```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
![icingaweb2](https://user-images.githubusercontent.com/11161944/160560580-991f6cbc-b168-4fcc-adc6-71f47ea9f002.png)


CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by nilmerg** [comment] 2022-03-29 08:48
Hi,

thanks for the report, but this is a known issue.

**Comment by nilmerg** [comment] 2022-03-29 08:48
Duplicate of #4711

**Closed by nilmerg** 2022-03-29 08:48 UTC
