### ISSUE TITLE
allow regex for username in roles.ini

### ISSUE THREAD

**Issue by djtecha** [Icinga/icingaweb2#2814] opened 2017-04-10 22:05 UTC
Im trying to create a readonly user and allow everyone that can get through my nginx authorization proxy to fall into a group. But it appears that I'm not allowed to use a regex for a username? Any ideas? When I log in I get my username showing up as first.last but I don't have any permissions since the username isn't defined anywhere.

roles.ini
```
[readonly]
users = "*"
groups = "users"
permissions = "*"
```
authentication.ini
```
[autologin]
strip_username_regexp = ""
backend = "external"
```

**Comment by lippserd** [comment] 2017-09-21 15:10
Hi,

Thanks for the report. I close this as duplicate of #2816.

Best regards,
Eric

**Closed by lippserd** 2017-09-21 15:10 UTC
Labels: duplicate

**Comment by lippserd** [comment] 2017-10-04 12:16
Sorry, this is a duplicate of #2915.
