### ISSUE TITLE
After upgrade to 2.5.0 can't update preferences

### ISSUE THREAD

**Issue by deric** [Icinga/icingaweb2#3177] opened 2017-12-03 12:28 UTC
After upgrading to `2.5.0-1.jessie` "Service grid" dashlet got lost from the main dashboard and I can't add it again. In fact I can't update any preferences for my user:
```
Cannot fetch preferences for user from database

#0 /usr/share/icingaweb2/application/forms/PreferenceForm.php(93): Icinga\User\Preferences\Store\DbStore->load()
#1 /usr/share/php/Icinga/Web/Form.php(1154): Icinga\Forms\PreferenceForm->onSuccess()
#2 /usr/share/icingaweb2/application/controllers/AccountController.php(68): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\AccountController->indexAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
```

I've upgraded DB backend for main `icinga2` following [upgrade steps](https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#upgrading-postgresql-db).

Are there any changes for `icingaweb2`? I'm using postgresql 9.6 backend DB.

**Comment by ggzengel** [comment] 2017-12-03 17:55
You have to upgrade your icingaweb2 DB.
There is an issue #3175

Have a look here:
/usr/share/icingaweb2/etc/schema

**Comment by deric** [comment] 2017-12-03 18:59
Right, I would expect some mention in the upgrade instructions. But maybe I've overlooked it. So for PostgreSQL:
```
cd /usr/share/icingaweb2/etc/schema/pgsql-upgrades
psql -U icinga2 -d icinga2_web -p 5432 < 2.5.0.sql
```

**Comment by deric** [comment] 2017-12-03 19:03
Nope. Same problem, even after updating the schema.

**Comment by deric** [comment] 2017-12-05 07:21
It looks like it's necessary to clear cookies in browser after the upgrade.

**Comment by Al2Klimov** [comment] 2017-12-19 14:42
I'm afraid the multi-AD support has changed the `User` class which we serialize in the session. (Hello #2292!)

We've changed the attributes containing the user name so your username effectively becomes NULL in your session.

**Comment by lippserd** [comment] 2018-01-17 11:24
Duplicate of #3277.

**Closed by lippserd** 2018-01-17 11:24 UTC
Labels: duplicate
