### ISSUE TITLE
filter problem in dashlet

### ISSUE THREAD

**Issue by maelig** [Icinga/icingaweb2#3335] opened 2018-01-31 15:06 UTC
I set up a filter in a dashlet with different rules. I want to exclude from the view of services belonging to a service group named BO. But when a service belongs to several groups of services including BO (see Attachmentt), the service is not excluded when it should. So, the filter does not work.

![screenshot-monitoring services local-2018-01-31-16-03-41](https://user-images.githubusercontent.com/7013790/35630053-94dd6a9c-06a0-11e8-8312-9ca016fe81b3.png)

* Icinga Web 2 version and modules : icingaweb2 => 2.4.1-1
* Version used (`icinga2 --version`): icinga2 2.6.1-1
* Operating System and version: Ubuntu 14.04 trusty

**Comment by lippserd** [comment] 2018-02-26 08:26
Hi,

Thanks for the report. Unfortunately excluding services with such a filter is not possible yet. We already have report open related to hostgroups open for this issue so I'll close this one as duplicate of #2934.

Best regards,
Eric

**Closed by lippserd** 2018-02-26 08:26 UTC
