### ISSUE TITLE
Icingaweb 2.6.3 Menu failes to load if no BP filter defined.

### ISSUE THREAD

**Issue by lokidaibel** [Icinga/icingaweb2#3859] opened 2019-07-12 04:42 UTC
I am not sure if this is a BP Module Bug or a Icingaweb2 bug. I will place it here but if i am wrong just tell me and i will migrate this to the Icingaweb2 Git Repo.

## Describe the bug
If there is no Prefix Filter defined for a Role in Icingaweb2 2.6.3 the whole Sidebar will Crash with:

ErrorException in /usr/share/php/Icinga/Web/Navigation/Renderer/NavigationItemRenderer.php:182 with message: Uninitialized string offset: 0

Adding any Filter to the User Role fix the Issue. This should not be needed because there can be user with noch Filter at all. 

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Update to Icinga 2.6.3 with a user role defined with no Bp Filter Attribute.
2. Try to load the Website

## Expected behavior
Normal Loading of the website.

## Screenshots
![grafik](https://user-images.githubusercontent.com/13196987/61102831-dac24280-a46f-11e9-8652-fd765aabd2aa.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.3
* Web browser used: Chrome - but should apply to any cause its a PHP Error
* Icinga 2 version used (`icinga2 --version`): 2.10.5
* PHP version used (`php --version`): 7.1.8
* Server operating system and version: RHEL 7.6

## Additional context

**Comment by nilmerg** [comment] 2019-07-12 05:37
Hi, that's a bug in Icinga Web 2. I transferred the issue already.

Though, the cause for this bug is related to your bp config, where you somehow managed to get a process without name into. That also explains why setting a filter solved it. (The process has no name so a filter cannot match it.) Check your configs whether you have such a process and give it a name, you then shouldn't need to set a filter.

**Closed** 2019-07-12 05:44 UTC
Labels: area/navigation, bug
