### ISSUE TITLE
Icinga Web 2 can not deal with different timestamp formats from LDAP-like directories

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2#2794] opened 2017-03-15 09:05 UTC
Hi,

A customer of mine uses eDirectory as directory service. Using it as authentication backend for users and groups works well save for listing groups with their members. Using the debuglog of Icinga Web 2 shows which query is used to list all members of a group which works from commandline. Another logline shows that it can not parse the timestamp and Icinga Web 2 seems to stop parsing the query results when it can not parse the timestamps.

     2017-03-15T09:17:44.933545+01:00 examplehost icingaweb2[25561]: Failed to parse "20170210074017Z" based on the ASN.1 standard (GeneralizedTime) in repository "eDirectory Gruppen".

The only functionality affected by this is the membership listing in Configuration->Authentication->User Groups

I do have some extra information on this issue I am not allowed to post here. If you need more background, just ask me directly.

Cheers,
Thomas

**Comment by widhalmt** [comment] 2017-03-16 08:24
Additionally (or alternatively) use some sort of error-handling where unknown timestamps do not result in group members not being listed. e.g. use "N/A" as timestamp if it can not converted but do not stop processing the rest of the queries.

**Comment by lippserd** [comment] 2017-09-21 15:08
Hi Thomas,

Thanks for the port. I close this as duplicate of #2816 because all the action is going on there.

Cheers,
Eric

**Closed by lippserd** 2017-09-21 15:08 UTC
Labels: duplicate
