### ISSUE TITLE
Show User model properties in Account view

### ISSUE THREAD

**Issue by UiP9AV6Y** [Icinga/icingaweb2#5267] opened 2024-09-26 06:05 UTC
For easier debugging of authentication/authorization issues i would like to know what information Icingaweb2 has of me as a user. As such i would suggest a read-only table/list of all properties of the User model in the Account view; currently only the Preferences are shown. For Roles/Permissions it would probably suffice to show the name attributes of the models.

Currently there is no easy way to debug issues with permissions as i have no idea what roles/permissions apply to a user and if it is an issue with the permissions or if the user backend provided insufficient information.

**Comment by nilmerg** [comment] 2024-09-26 06:24
> Currently there is no easy way to debug issues with permissions as i have no idea what roles/permissions apply to a user

Navigate in the sidebar to *Access Control* -> *Audit* (Tab) and enter the username

>  if the user backend provided insufficient information.

Turn on debug log. The groups a user is associated with are logged during login.

--

For all the other things, this is a:

**Comment by nilmerg** [comment] 2024-09-26 06:24
Duplicate of #5264

**Closed by nilmerg** 2024-09-26 06:24 UTC
