### ISSUE TITLE
502 Bad Gateway with PHP 7.3.7

### ISSUE THREAD

**Issue by SynPrime** [Icinga/icingaweb2#3843] opened 2019-07-03 21:28 UTC
## Describe the bug
After upgrading PHP 7.3.6 to 7.3.7, I get a 502 Bad Gateway if I want to access icingaweb2. Other PHP sites are working, so I think this must be a problem of icingaweb2!?

I dind't change any config after the upgrade. The previous version was working.

## To Reproduce

1. Upgrade PHP to 7.3.7

## Your Environment

* Icinga Web 2 version and modules (System - About): icingaweb2 2.6.3
* Web browser used: Google Chrome
* Icinga 2 version used (`icinga2 --version`): 2.10.5
* PHP version used (`php --version`): 7.3.7
* Server operating system and version: Linux Debian 9
* Webserver: nginx 1.17.1

## Logfile of Webservice

`failed (104: Connection reset by peer) while reading response header from upstream ... request: "GET /icingaweb2/authentication/login HTTP/1.1"`

**Comment by nilmerg** [comment] 2019-07-04 06:07
Hi, I can't find version 7.3.7 anywhere? [7.3.6 is currently latest](https://www.php.net/downloads.php)

**Comment by SynPrime** [comment] 2019-07-04 08:08
Hi, on GitHub PHPs latest version is 7.3.7 (https://github.com/php/php-src/releases).

**Comment by reubenfarrelly** [comment] 2019-07-04 11:23
I'm also seeing this since upgrading from 7.3.6 to 7.3.7.  All other apps/websites hosted locally are working fine ... except for icingaweb2.  I've also upgraded to -git master and still seeing the same problem.

**Comment by reubenfarrelly** [comment] 2019-07-08 13:48
Adding to my previous comment, I have just tested and confirmed that if I downgrade php to 7.3.6 again, icingaweb2 works just fine.  So it seems this issue may be reproducible, and really is specific to 7.3.7.

I am using Gentoo x86_64 kept very up to date:

thunderstorm ~ # apache2 -V
Server version: Apache/2.4.39 (Unix)
Server built:   Apr 27 2019 19:23:42
Server's Module Magic Number: 20120211:84
Server loaded:  APR 1.7.0, APR-UTIL 1.6.1
Compiled using: APR 1.7.0, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_PROC_PTHREAD_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/usr"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/var/run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="/etc/apache2/mime.types"
 -D SERVER_CONFIG_FILE="/etc/apache2/httpd.conf"
thunderstorm ~ #

**Comment by reubenfarrelly** [comment] 2019-07-10 13:57
The issue is probably caused by this bug in PHP:

https://bugs.php.net/bug.php?id=78230

After upgrading to the fixed version the problem has completely gone away for me.

**Comment by nilmerg** [comment] 2019-07-10 14:00
Thanks for the heads up @reubenfarrelly! @SynPrime does the fixed version also help on your end?

**Comment by SynPrime** [comment] 2019-07-10 14:33
> After upgrading to the fixed version the problem has completely gone away for me.

Which fixed version do you mean? PHPs current version is still 7.3.7

**Comment by dnsmichi** [comment] 2019-07-11 07:06
Since @reubenfarrelly is using Gentoo, I would believe that a patched makefile with a different branch (or master) is now used. For everyone else, a new PHP release or packages with that patch are needed.

@SynPrime in your case, Debian 9 doesn't provide PHP 7.3 in their repos. I would believe that you're using an external repository. Open a bug in their tracker to let them know about this problem.

**Comment by reubenfarrelly** [comment] 2019-07-11 12:55
@dnsmichi You're spot on with your observation.  I had (accidentally) omitted to state that yes this was a Gentoo ebuild bump.
The Gentoo commit states that upstream " silently re-released PHP 7.3.7": https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=7ffe8144d96a37c682dd28655764778f46114bf2
The ebuild itself wasn't changed, but the hash of php-7.3.7.tar.xz certainly has.

**Comment by nilmerg** [comment] 2019-07-15 05:44
Thanks again @reubenfarrelly for clearing this up. It's fixed in PHP itself, so not an issue for us -> Closed.

**Closed by nilmerg** 2019-07-15 05:44 UTC
