### ISSUE TITLE
[dev.icinga.com #13010] Configuration item to change the default Limit

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2#2602] opened 2016-10-30 21:35 UTC
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13010

**Created by Foxeronie on 2016-10-30 21:35:44 +00:00**

Assignee: _elippmann_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-14 17:34:09 +00:00 (in Redmine)_

---

Hi!

Is it possible to add an option where I can select the default limit?
Currently when I select Host Problems, Service Problems, etc. the default limit is 25.
It would be great if I can select a default of 50 or 100.

Best regards,
Patrick

**Changesets**

_2016-12-14 17:25:18 +00:00_ by _(unknown)_ f035442988a9fe477e39fdad1ba1949dfb7903a2

    Add user preference for default number of items per page
    
    refs #13010

**Comment by Al2Klimov** [comment] 2017-02-09 16:42
Is this OK (except German translation)?

I also discovered some 25s. We should decide case-by-case what to do with them:
`git ls-files -z |grep -zEe $'\\.php$' -e $'\\.phtml$' |grep -zvEe $'^library/vendor/' |grep -zvxFe modules/monitoring/test/php/library/Monitoring/Plugin/PerfdataTest.php -e library/Icinga/Web/Controller.php |xargs -0 grep --color=always -nFwe 25`

**Comment by lippserd** [comment] 2017-09-21 10:08
Closing this as duplicate of #2859.

**Closed by lippserd** 2017-09-21 10:08 UTC
Labels: enhancement, feedback
