### ISSUE TITLE
Non-English characters from Comments displayed as "????"

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Icinga/icingaweb2#2858] opened 2017-06-05 14:16 UTC
Hello.

We try to use non-English (for example Russian) words in the Comments to the Host/Service or Comments in Downtime. As a result, in Icinga-Web-2 interface instead of normal characters are displayed as "????"

Environment:
* Icinga Web 2 version and modules (System - About): 2.4.1
* Version used (`icinga2 --version`): r2.6.3-1
* Operating System and version: Debian GNU/Linux 8.7 (jessie)
* Enabled features (`icinga2 feature list`): api checker command graphite ido-mysql mainlog notification perfdata
* Config validation (`icinga2 daemon -C`): no errors

Part of /etc/icingaweb2/resources.ini about DB:

```
[icingaweb_db]
type = "db"
db = "mysql"
host = "localhost"
port = "3306"
dbname = "icingawebdb"
username = "icingawebdb-usr"
password = "***"
charset = "utf8"
persistent = "0"
```

**Comment by majales** [comment] 2017-06-12 07:36
Hi 
I can confirm this problem. Wednesday last week I created issue on Icinga Director GitHub ( https://github.com/Icinga/icingaweb2-module-director/issues/960 ) I thought it was Icinga Director Problem and then I thought I made mistake in Icinga setup. Issue was rejected by Thomas Gelf and he was right. It is definitelly Icingaweb2 problem. It cannot corectly display unicode characters. It affect real names of users (with accented characters) and comments of downtimes (with accented characters)

I have created test downtime with accented characters from Czech alphabeth. This is beggining object from icinga2 with comment:

> icinga2 object list --type=Downtime
Object 'icinga-tstclient01.domain.ltd!users!icinga-01.domain.ltd-1497020973-8' of type 'Downtime':
  % declared in '/var/lib/icinga2/api/packages/_api/icinga-01.domain.ltd-1491815260-1/conf.d/downtimes/icinga-tstclient01.domain.ltd!users!icinga-01.domain.ltd-1497020973-8.conf', lines 1:0-1:68 
  >\* __name = "icinga-tstclient01.domain.ltd!users!icinga-01.domain.ltd-1497020973-8"
  >\* author = "admin"
    % = modified in '/var/lib/icinga2/api/packages/_api/icinga-01.domain.ltd-1491815260-1/conf.d/downtimes/icinga-tstclient01.domain.ltd!users!icinga-01.domain.ltd-1497020973-8.conf', lines 2:2-2:17
  >\* comment = "+ěšččáýíéžáíéíáé"

It shows correctly as icinga object ( console with UTF8 locale ). But on Icingaweb2 webpage it looks like this:
![icingaweb2_bad_charset](https://user-images.githubusercontent.com/11310917/27023354-73119696-4f52-11e7-8fc1-65d1edfa013f.png)

**Comment by lippserd** [comment] 2017-06-20 11:38
Hi guys,

The default MySQL server character set is latin1. If you did not change these settings, i.e. `character-set-server` and `collation-server` you should not use utf8 as character set in your resource configuration. Either leave the configuration empty, or set it to `latin1`.
If you really want to use UTF-8, you have to change your server's character set and recreate the full Icinga database.

I close this issue but please give me feedback whether this helped.

Best regards,
Eric

**Closed by lippserd** 2017-06-20 11:38 UTC

**Comment by majales** [comment] 2017-06-22 05:49
Hi, 
I´m sorry to open this issue again. In fact there is nothing about setting mysql to utf8 in official icinga2 documentation ( https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/getting-started#setting-up-mysql-db ). I´m also using CentOS 7.

I already tried to convert icinga to utf8 but it makes icingaweb2 interface to throw errors and rendered it nonworkable. Could you please provide some guide how to convert icinga db to utf8 from latin1?

**Comment by Aleksey-Maksimov** [comment] 2017-09-27 13:45
Hello, majales. You solved the problem?
Solution "recreate the full Icinga database" looks like something dangerous.

**Comment by lippserd** [comment] 2017-09-27 13:49
Hi,

Setting the character set to `latin1` should be sufficient.

Cheers,
Eric

**Comment by majales** [comment] 2017-09-27 16:39
I had backup of db of course.. And tried it on test installation. 

I had to prepare another installation of Icinga2 with Icingaweb2 on Ubuntu 16 LTS, and suprisingly this time everything looks fine.. I had double checked icingaweb2 db tables and they are the same on both Centos and Ubuntu, so there should be something different in Icingaweb2 source files .. 

I haven't tried to upgrade packages on CentOS 7 yet, maybe it is already solved..

**Comment by majales** [comment] 2017-09-27 16:46
Well, there is one difference between Centos7 and Ubuntu16 LTS installation

on CentOS7:
version: 5.5.52-MariaDB

On Ubuntu 16 LTS
version: 5.7.19-0ubuntu0.16.04.1

I don't know if it is making any sense..

**Comment by Aleksey-Maksimov** [comment] 2017-09-27 17:08
In my case, using these versions:

- Debian GNU/Linux 8.9 (jessie)
- mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3

Any idea how can I solve this problem without breaking current data in DB?

**Comment by majales** [comment] 2017-09-27 17:32
I can make test, I have tested and modified ansible role for icinga automatic deploy https://github.com/juju4/ansible-icinga2 .. so if I'll find spare time I will clone another machine from template and try to deploy it on CentOS 7 again..

**Comment by Animancorda** [comment] 2018-05-29 11:15
Hello community. I meet same problem and the way i resolve it wat next: go to Icinga Web 2 -> Configuration -> Aplication -> Resources. Choose there your DB and change there "Character Set" to "latin1".

systemctl reload apache2
systemctl reload icinga2
systemctl reload mysql.service

Now symbols looks correctly.

`![default](https://user-images.githubusercontent.com/38096921/40655650-b0544e1a-634a-11e8-8904-78ead01d6947.PNG)
`

**Comment by majales** [comment] 2018-05-29 12:37
Animancorda: Thanx for your resolution..I will try it. Which resource did you changed? icingaweb_db or icinga_ido?

**Comment by Animancorda** [comment] 2018-05-30 06:09
@majales, i changed it for all my resources: icinga_ido, icingaweb_db, director_db. Btw, when i created those DB, i choosed charset - utf8. Looks like changing DB charset does not break DB. So there **no need** in"recreate" data bases with total data loss.

**Comment by islander** [comment] 2018-06-07 02:52
@Animancorda not helped for me, still get question marks instead of cyrillic names.

could you please show yours `SHOW CREATE TABLE icinga_hosts` from IDO database?

**Comment by Animancorda** [comment] 2018-06-08 07:02
@islander, check your hosts fields "Display name" and "Notes". Looks like Icinga changed fields content to unknown symbols. Unfortunately i meet this ploblem once, so i had to change it content to normal by my hands.

Got error "no database selected". Could you provide full example of command?

**Comment by islander** [comment] 2018-06-12 22:59
@Animancorda I replaced MySQL IDO with PostgreSQL IDO, now I have correct names in icingaweb2, but some encoding issues still present:

- Overview - Hosts - Search... - can filter hosts only typing lowercase cyrillic character
- No UTF-8 headers in notification e-mail (see screenshot)
![icinga_utf8](https://user-images.githubusercontent.com/894474/41321430-a43b67f2-6eef-11e8-8cd0-8489f5018bcb.jpg)

> Got error "no database selected". Could you provide full example of command?

You should select icinga database first (check DB name first with `show databases` command), and then:
```
    USE icinga;
    SHOW CREATE TABLE icinga_hosts
```

**Comment by islander** [comment] 2018-06-12 23:34
@lippserd could you please re-open this issue, or should I create new?
